/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2020-04-11 11:44:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.clinic.basicInfo.ServiceItemCost;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ServiceItemCostView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(20);
    _jspx_dependants.put("/WEB-INF/tags/my-grid-search.tag", Long.valueOf(1580195789528L));
    _jspx_dependants.put("/WEB-INF/tags/footer.tag", Long.valueOf(1580195770283L));
    _jspx_dependants.put("/WEB-INF/tags/buttonPermission.tag", Long.valueOf(1580195815571L));
    _jspx_dependants.put("/WEB-INF/tags/searchButton.tag", Long.valueOf(1580195783637L));
    _jspx_dependants.put("/WEB-INF/tags/pageHeader.tag", Long.valueOf(1580195811013L));
    _jspx_dependants.put("/WEB-INF/tags/my-grid-function.tag", Long.valueOf(1580195828904L));
    _jspx_dependants.put("/WEB-INF/kendo-taglibs.tld", Long.valueOf(1580195833241L));
    _jspx_dependants.put("/WEB-INF/tags/aPermission.tag", Long.valueOf(1580195972112L));
    _jspx_dependants.put("/WEB-INF/tags/message.tag", Long.valueOf(1580195883269L));
    _jspx_dependants.put("/WEB-INF/tags/searchGridMultipleDelete.tag", Long.valueOf(1580195772803L));
    _jspx_dependants.put("/WEB-INF/tags/exportToExcel.tag", Long.valueOf(1580195913238L));
    _jspx_dependants.put("/WEB-INF/tags/searchGridOperation.tag", Long.valueOf(1580195820211L));
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1580195752738L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/matab/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323245778000L));
    _jspx_dependants.put("/WEB-INF/tags/my-grid-schema-field.tag", Long.valueOf(1580195882670L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/matab/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/fn.tld", Long.valueOf(1323245778000L));
    _jspx_dependants.put("/WEB-INF/tags/multiSelect.tag", Long.valueOf(1580195871123L));
    _jspx_dependants.put("/WEB-INF/tags/my-grid-column.tag", Long.valueOf(1580195851012L));
    _jspx_dependants.put("/WEB-INF/tags/dialogConfirm.tag", Long.valueOf(1580195821308L));
    _jspx_dependants.put("/WEB-INF/tags/checkbox.tag", Long.valueOf(1580195763254L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	String basePath = request.getAttribute("controllerBasePath").toString();

      out.write('\n');
      out.write('\n');
      if (_jspx_meth_base_005fpageHeader_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<div id=\"modal-copyItem\" style=\"display: inline;\">\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_base_005fbuttonPermission_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"uk-container uk-container-center my-uk-container\" style=\"margin-bottom: 4px; \">\n");
      out.write("\t<form class=\"uk-form\" id=\"mainForm\">\n");
      out.write("\t\t<div class=\"uk-grid uk-grid-preserve\">\n");
      out.write("\t\t\t");
      if (_jspx_meth_base_005fmultiSelect_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_base_005fmultiSelect_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t");
      if (_jspx_meth_base_005fcheckbox_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("</div>\n");
      out.write("\n");
      if (_jspx_meth_base_005fmy_002dgrid_002dsearch_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_base_005ffooter_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("    function grid_copyItem(e) {\n");
      out.write("        var data = this.dataItem($(e.target).closest(\"tr\"));\n");
      out.write("        var sic_id = data.id;\n");
      out.write("        if (e) {\n");
      out.write("            var modal;\n");
      out.write("            $(function () {\n");
      out.write("                var popUpUrl = '");
      out.print(basePath);
      out.write("' + \"/popup/copyServiceItemCost\";\n");
      out.write("                $.get(popUpUrl, function (data) {\n");
      out.write("                    $(\"#modal-copyItem\").empty();\n");
      out.write("                    var id = \"modal-copyItem_popup\";\n");
      out.write("                    $(\"#modal-copyItem\").append('<div id=\"' + id + '\" class=\"uk-modal\" data-serviceItemCostId=\"' + sic_id + '\">');\n");
      out.write("                    $(\"#\" + id).append(data);\n");
      out.write("                    modal = new $.UIkit.modal.Modal(\"#\" + id);\n");
      out.write("                    $(\"#\" + id).on(\n");
      out.write("                        {\n");
      out.write("                            'uk.modal.hide': function () {\n");
      out.write("                                $(\"#modal-copyItem\").empty();\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                    );\n");
      out.write("                    modal.show();\n");
      out.write("                });\n");
      out.write("            });\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function getSearchObject(){\n");
      out.write("        var searchObj = {};\n");
      out.write("        searchObj.serviceValues = $(\"#serviceValues_multiSelect\").val();\n");
      out.write("        var arrayDataItems=$(\"#serviceValues_multiSelect\").data(\"kendoMultiSelect\")._dataItems;\n");
      out.write("        if(arrayDataItems!=undefined &&arrayDataItems.length>0){\n");
      out.write("            var service_item_valueText='';\n");
      out.write("            for(var i=0;i<arrayDataItems.length;i++){\n");
      out.write("                service_item_valueText+=arrayDataItems[i].ComboCaption+' , ';\n");
      out.write("            }\n");
      out.write("           // searchObj.services_text=service_item_valueText.substring(0,service_item_valueText.length-3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        searchObj.groupValues = $(\"#groupValues_multiSelect\").val();\n");
      out.write("         arrayDataItems=$(\"#groupValues_multiSelect\").data(\"kendoMultiSelect\")._dataItems;\n");
      out.write("        if(arrayDataItems!=undefined &&arrayDataItems.length>0){\n");
      out.write("            var group_valueText='';\n");
      out.write("            for(var j=0;j<arrayDataItems.length;j++){\n");
      out.write("                group_valueText+=arrayDataItems[j].ComboCaption+' , ';\n");
      out.write("            }\n");
      out.write("            searchObj.group_text=group_valueText.substring(0,group_valueText.length-3);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        searchObj.showCurrentService = $(\"#showCurrentService\").prop('checked');\n");
      out.write("        return searchObj;\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    $(document).ready(function () {\n");
      out.write("        $(\"#showCurrentService\").prop('checked', 'checked');\n");
      out.write("\t});\n");
      out.write("\n");
      out.write("//    $('#update-btn').on(\"click\", function (e) {\n");
      out.write("    function updateServiceitemcost(){\n");
      out.write("        $.getJSON(basePath + 'update', function (result) {\n");
      out.write("            if (result.state == \"success\") {\n");
      out.write("                grid = $(\"#searchGrid\").data(\"kendoGrid\");\n");
      out.write("                grid.dataSource.page(grid.dataSource.page());\n");
      out.write("                alertify.success(result.message);\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function printDetail(){\n");
      out.write("        var searchJsonString = \"{}\";\n");
      out.write("        if(typeof(getSearchObject)==\"function\"){\n");
      out.write("            searchJsonString = JSON.stringify(getSearchObject());\n");
      out.write("            searchJsonString = searchJsonString.replace(/\\//g, ':@:');\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        var urlGrid = basePath + \"print/serviceItemCostDetail/\" + searchJsonString;\n");
      out.write("\n");
      out.write("        window.open(urlGrid);\n");
      out.write("\n");
      out.write("        if(typeof(doAfterSearch)==\"function\"){\n");
      out.write("            doAfterSearch(searchJsonString);\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    }\n");
      out.write("\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_base_005fpageHeader_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:pageHeader
    org.apache.jsp.tag.web.pageHeader_tag _jspx_th_base_005fpageHeader_005f0 = (new org.apache.jsp.tag.web.pageHeader_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fpageHeader_005f0);
    _jspx_th_base_005fpageHeader_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005fpageHeader_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fpageHeader_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005fbuttonPermission_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:buttonPermission
    org.apache.jsp.tag.web.buttonPermission_tag _jspx_th_base_005fbuttonPermission_005f0 = (new org.apache.jsp.tag.web.buttonPermission_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fbuttonPermission_005f0);
    _jspx_th_base_005fbuttonPermission_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(15,4) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f0.setKey("com.artonis.clinic.basicInfo.serviceItemCost.update");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(15,4) name = id type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f0.setId("update-btn");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(15,4) name = classNames type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f0.setClassNames("uk-button uk-button-success");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(15,4) name = onClick type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f0.setOnClick("updateServiceitemcost()");
    _jspx_th_base_005fbuttonPermission_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fbuttonPermission_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005fmultiSelect_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:multiSelect
    org.apache.jsp.tag.web.multiSelect_tag _jspx_th_base_005fmultiSelect_005f0 = (new org.apache.jsp.tag.web.multiSelect_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmultiSelect_005f0);
    _jspx_th_base_005fmultiSelect_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(22,3) name = serverFilter type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmultiSelect_005f0.setServerFilter(new java.lang.Boolean(true));
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(22,3) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmultiSelect_005f0.setName("groupValues");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(22,3) name = styleClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmultiSelect_005f0.setStyleClass("small");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(22,3) name = multiSelectLoaderUrl type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmultiSelect_005f0.setMultiSelectLoaderUrl("combo/allGroup");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(22,3) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmultiSelect_005f0.setKey("com.artonis.clinic.basicInfo.service.group_id");
    _jspx_th_base_005fmultiSelect_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmultiSelect_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005fmultiSelect_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:multiSelect
    org.apache.jsp.tag.web.multiSelect_tag _jspx_th_base_005fmultiSelect_005f1 = (new org.apache.jsp.tag.web.multiSelect_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmultiSelect_005f1);
    _jspx_th_base_005fmultiSelect_005f1.setJspContext(_jspx_page_context);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(23,3) name = serverFilter type = java.lang.Boolean reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmultiSelect_005f1.setServerFilter(new java.lang.Boolean(true));
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(23,3) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmultiSelect_005f1.setName("serviceValues");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(23,3) name = styleClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmultiSelect_005f1.setStyleClass("small");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(23,3) name = multiSelectLoaderUrl type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmultiSelect_005f1.setMultiSelectLoaderUrl("combo/allService");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(23,3) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmultiSelect_005f1.setKey("com.artonis.clinic.basicInfo.service.name");
    _jspx_th_base_005fmultiSelect_005f1.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmultiSelect_005f1);
    return false;
  }

  private boolean _jspx_meth_base_005fcheckbox_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:checkbox
    org.apache.jsp.tag.web.checkbox_tag _jspx_th_base_005fcheckbox_005f0 = (new org.apache.jsp.tag.web.checkbox_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fcheckbox_005f0);
    _jspx_th_base_005fcheckbox_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(24,3) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fcheckbox_005f0.setName("showCurrentService");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(24,3) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fcheckbox_005f0.setKey("com.artonis.clinic.basicInfo.serviceItemCost.showCurrentService");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(24,3) name = divLableStyle type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fcheckbox_005f0.setDivLableStyle("width: 25%;");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(24,3) name = divCheckBoxStyle type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fcheckbox_005f0.setDivCheckBoxStyle("width: 10%;");
    _jspx_th_base_005fcheckbox_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fcheckbox_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005fmy_002dgrid_002dsearch_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:my-grid-search
    org.apache.jsp.tag.web.my_002dgrid_002dsearch_tag _jspx_th_base_005fmy_002dgrid_002dsearch_005f0 = (new org.apache.jsp.tag.web.my_002dgrid_002dsearch_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmy_002dgrid_002dsearch_005f0);
    _jspx_th_base_005fmy_002dgrid_002dsearch_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(29,0) name = selectable type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dsearch_005f0.setSelectable("single");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(29,0) name = printButtonIds type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dsearch_005f0.setPrintButtonIds("printDetail");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(29,0) name = printButtonNames type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dsearch_005f0.setPrintButtonNames("Detail");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(29,0) name = printButtonResoureceBundle type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dsearch_005f0.setPrintButtonResoureceBundle("com.artonis.clinic.basicInfo.serviceItemCost.print.detail");
    _jspx_th_base_005fmy_002dgrid_002dsearch_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_base_005fmy_002dgrid_002dsearch_005f0, null));
    _jspx_th_base_005fmy_002dgrid_002dsearch_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmy_002dgrid_002dsearch_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005fmy_002dgrid_002dcolumn_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:my-grid-column
    org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0 = (new org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f0);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0.setParent(_jspx_parent);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(30,1) name = title type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0.setTitle("com.artonis.clinic.basicInfo.serviceItemCost.group_id");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(30,1) name = field type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0.setField("group_name");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(30,1) name = width type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0.setWidth("50px");
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005fmy_002dgrid_002dcolumn_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:my-grid-column
    org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1 = (new org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f1);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1.setJspContext(_jspx_page_context);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1.setParent(_jspx_parent);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(31,1) name = title type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1.setTitle("com.artonis.clinic.basicInfo.serviceItemCost.service_id");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(31,1) name = field type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1.setField("service_name");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(31,1) name = width type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1.setWidth("50px");
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f1);
    return false;
  }

  private boolean _jspx_meth_base_005fmy_002dgrid_002dcolumn_005f2(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:my-grid-column
    org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag _jspx_th_base_005fmy_002dgrid_002dcolumn_005f2 = (new org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f2);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f2.setJspContext(_jspx_page_context);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f2.setParent(_jspx_parent);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(32,1) name = title type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f2.setTitle("com.artonis.clinic.basicInfo.serviceItemCost.cost");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(32,1) name = field type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f2.setField("totalCost");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(32,1) name = width type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f2.setWidth("50px");
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f2.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f2);
    return false;
  }

  private boolean _jspx_meth_base_005fmy_002dgrid_002dcolumn_005f3(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:my-grid-column
    org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag _jspx_th_base_005fmy_002dgrid_002dcolumn_005f3 = (new org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f3);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f3.setJspContext(_jspx_page_context);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f3.setParent(_jspx_parent);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(33,1) name = title type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f3.setTitle("com.artonis.clinic.basicInfo.employeeServiceAmount.fromDate");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(33,1) name = field type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f3.setField("fromDate");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(33,1) name = width type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f3.setWidth("50px");
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f3.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f3);
    return false;
  }

  private boolean _jspx_meth_base_005fmy_002dgrid_002dcolumn_005f4(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:my-grid-column
    org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag _jspx_th_base_005fmy_002dgrid_002dcolumn_005f4 = (new org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f4);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f4.setJspContext(_jspx_page_context);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f4.setParent(_jspx_parent);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(34,1) name = title type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f4.setTitle("com.artonis.clinic.basicInfo.employeeServiceAmount.toDate");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(34,1) name = field type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f4.setField("toDate");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(34,1) name = width type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f4.setWidth("50px");
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f4.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f4);
    return false;
  }

  private boolean _jspx_meth_base_005fmy_002dgrid_002dschema_002dfield_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:my-grid-schema-field
    org.apache.jsp.tag.web.my_002dgrid_002dschema_002dfield_tag _jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f0 = (new org.apache.jsp.tag.web.my_002dgrid_002dschema_002dfield_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f0);
    _jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f0.setParent(_jspx_parent);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(36,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f0.setName("service_text");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(36,4) name = type type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f0.setType("string");
    _jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005fmy_002dgrid_002dschema_002dfield_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:my-grid-schema-field
    org.apache.jsp.tag.web.my_002dgrid_002dschema_002dfield_tag _jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f1 = (new org.apache.jsp.tag.web.my_002dgrid_002dschema_002dfield_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f1);
    _jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f1.setJspContext(_jspx_page_context);
    _jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f1.setParent(_jspx_parent);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(37,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f1.setName("totalCost");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(37,4) name = type type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f1.setType("long");
    _jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f1.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmy_002dgrid_002dschema_002dfield_005f1);
    return false;
  }

  private boolean _jspx_meth_base_005fmy_002dgrid_002dfunction_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:my-grid-function
    org.apache.jsp.tag.web.my_002dgrid_002dfunction_tag _jspx_th_base_005fmy_002dgrid_002dfunction_005f0 = (new org.apache.jsp.tag.web.my_002dgrid_002dfunction_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmy_002dgrid_002dfunction_005f0);
    _jspx_th_base_005fmy_002dgrid_002dfunction_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005fmy_002dgrid_002dfunction_005f0.setParent(_jspx_parent);
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(39,4) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dfunction_005f0.setName("serviceItemCostCopy");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(39,4) name = styleClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dfunction_005f0.setStyleClass("uk-button-primary");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(39,4) name = functionClick type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dfunction_005f0.setFunctionClick("grid_copyItem");
    // /WEB-INF/pages/clinic/basicInfo/ServiceItemCost/ServiceItemCostView.jsp(39,4) name = text type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dfunction_005f0.setText("com.artonis.clinic.basicInfo.serviceItemCost.copyItem");
    _jspx_th_base_005fmy_002dgrid_002dfunction_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmy_002dgrid_002dfunction_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005ffooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:footer
    org.apache.jsp.tag.web.footer_tag _jspx_th_base_005ffooter_005f0 = (new org.apache.jsp.tag.web.footer_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005ffooter_005f0);
    _jspx_th_base_005ffooter_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005ffooter_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005ffooter_005f0);
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write('\n');
      out.write('	');
      if (_jspx_meth_base_005fmy_002dgrid_002dcolumn_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_base_005fmy_002dgrid_002dcolumn_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_base_005fmy_002dgrid_002dcolumn_005f2(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_base_005fmy_002dgrid_002dcolumn_005f3(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_base_005fmy_002dgrid_002dcolumn_005f4(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_base_005fmy_002dgrid_002dschema_002dfield_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("    ");
      if (_jspx_meth_base_005fmy_002dgrid_002dschema_002dfield_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write("\n");
      out.write("    \n");
      out.write("    ");
      if (_jspx_meth_base_005fmy_002dgrid_002dfunction_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\n');
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
