/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2018-04-30 12:55:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.clinic.patient.PenVisit.fileBaseItems;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.artonis.clinic.patient.model.PatientConstValue.PatientFileFilterTypeEnum;

public final class PatientFile_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1513760541684L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/matab/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323245778000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.artonis.clinic.patient.model.PatientConstValue.PatientFileFilterTypeEnum");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"p-patientFile\" dir=\"ltr\">\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<div id=\"p-patientFileContainer\" style=\" width:100%; height:100%\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t$(\"#p-patientFile\").dialog({\r\n");
      out.write("\t\theight : 500,\r\n");
      out.write("\t\twidth : 1000,\r\n");
      out.write("\t\tautoOpen : false,\r\n");
      out.write("\t\tshow : {\r\n");
      out.write("\t\t\teffect : \"blind\",\r\n");
      out.write("\t\t\tduration : 500\r\n");
      out.write("\t\t},\r\n");
      out.write("\t\thide : {\r\n");
      out.write("\t\t\teffect : \"slide\",\r\n");
      out.write("\t\t\tduration : 500\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\t$(\"#p-patientFile-id-txt\").click(function() {\r\n");
      out.write("\t\t$(\"#p-patientFile\").dialog(\"open\");\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tjQuery('body').bind('click', function(e) {\r\n");
      out.write("\t\tif (jQuery('#p-patientFile').dialog('isOpen') && !jQuery(e.target).is('.ui-dialog, a') && !jQuery(e.target).closest('.ui-dialog').length && event.target.nodeName != \"H2\") {\r\n");
      out.write("\t\t\tjQuery('#p-patientFile').dialog('close');\r\n");
      out.write("\t\t}\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tloadPatientFile();\r\n");
      out.write("\t\r\n");
      out.write("\tfunction loadPatientFile() {\r\n");
      out.write("\t\tvar filterType = ");
      out.print(PatientFileFilterTypeEnum.HANDWRITING.getValue());
      out.write(";\r\n");
      out.write("\t\t$.getJSON(\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" + \"clinic/patient/penVisit/loadByPatient/\" + ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${patientId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(" + \"/\" + filterType, function(data) {\r\n");
      out.write("\t\t\t$(\"#patientFile-for-test-inner\").append(data.data);\r\n");
      out.write("\t\t\t$(\"#patientFile-for-test-inner-1\").append(data.data);\r\n");
      out.write("\t\t\t$(\"#patientFile-for-test-inner-1\").accordion({\r\n");
      out.write("\t\t\t\theightStyle : \"content\",\r\n");
      out.write("\t\t\t\tcollapsible : true\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#patientFile-for-test-inner-1\").accordion(\"refresh\");\r\n");
      out.write("\t\t\t$(\"#p-patientFileContainer\").append(data.data);\r\n");
      out.write("\t\t\t$(\"#p-patientFileContainer\").accordion({\r\n");
      out.write("\t\t\t\theightStyle : \"content\",\r\n");
      out.write("\t\t\t\tcollapsible : true\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$(\"#p-patientFileContainer\").accordion(\"refresh\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar headerArray = $('h3[id^=\"ui-accordion-patientFile-for-test-inner-header\"]');\r\n");
      out.write("\t\t\tfor (var i = 0; i < headerArray.length; i++) {\r\n");
      out.write("\t\t\t\theaderArray.eq(i).css(\"background\", \"-webkit-gradient(linear, left top, left bottom, color-stop(0%,rgba(255,244,180,1)), color-stop(100%,rgba(251,221,83,1)))\");\r\n");
      out.write("\t\t\t\theaderArray.eq(i).css(\"border\", \"1px solid #d3d3d3\");\r\n");
      out.write("\t\t\t\theaderArray.eq(i).css(\"font-weight\", \"normal\");\r\n");
      out.write("\t\t\t\theaderArray.eq(i).css(\"color\", \"#555555\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar patientFileArray = $('#patientFile-for-test-inner [id^=\"accordion-patientFile-\"]');\r\n");
      out.write("\t\t\tfor (var j = 0; j < patientFileArray.length; j++) {\r\n");
      out.write("\t\t\t\t$(\"#\" + patientFileArray[j].id).accordion({\r\n");
      out.write("\t\t\t\t\theightStyle : \"content\",\r\n");
      out.write("\t\t\t\t\tcollapsible : true\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\r\n");
      out.write("\t\t\tfancySizeCorrection();\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction fancySizeCorrection(){\r\n");
      out.write("\t\t$(\".fancybox\").each(function (item) {\r\n");
      out.write("\t\t\tvar sourceDiv = $(this);\r\n");
      out.write("\t\t\tvar divWidth = sourceDiv.width();\r\n");
      out.write("\t\t\tvar url = sourceDiv.css(\"background-image\");\r\n");
      out.write("\t\t\turl = url.substring(5, url.length - 2);\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar img = new Image();\r\n");
      out.write("\t\t\timg.onload = function () {\r\n");
      out.write("\t\t\t\tsourceDiv.css(\"background-size\", img.width / 3.5 + 'px');\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\timg.src = url;\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("    $(\".fancybox\").fancybox({\r\n");
      out.write("        'width':$(window).width() * 0.85,\r\n");
      out.write("        'height':$(window).height() * 0.85,\r\n");
      out.write("        'autoDimensions':false,\r\n");
      out.write("        'autoSize':false,\r\n");
      out.write("        'mouseWheel': false,\r\n");
      out.write("        afterShow: function() {\r\n");
      out.write("        },\r\n");
      out.write("        beforeShow: function() {\r\n");
      out.write("\t\t\tthis.element.css(\"height\", \"99%\");\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar sourceDiv = this.element;\r\n");
      out.write("\t\t\tvar url = sourceDiv.css(\"background-image\");\r\n");
      out.write("\t\t\turl = url.substring(5, url.length - 2);\r\n");
      out.write("\r\n");
      out.write("\t\t\tvar img = new Image();\r\n");
      out.write("\t\t\timg.onload = function () {\r\n");
      out.write("\t\t\t\tsourceDiv.css(\"background-size\", img.width / 1.5 + 'px');\r\n");
      out.write("\t\t\t};\r\n");
      out.write("\t\t\timg.src = url;\r\n");
      out.write("        },\r\n");
      out.write("        afterClose: function() {\r\n");
      out.write("\t\t\t$(\".imageFrame div\").css(\"display\", \"\");\r\n");
      out.write("\t\t\t$(\".imageFrame div\").css(\"width\", \"auto\");\r\n");
      out.write("\t\t\t$(\".imageFrame div\").css(\"height\", \"250px\");\r\n");
      out.write("\t\t\tfancySizeCorrection();\r\n");
      out.write("        },\r\n");
      out.write("        beforeClose: function(){\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\tfunction emptyPatientFile() {\r\n");
      out.write("\t\t$(\"#p-patientFileContainer\").empty();\r\n");
      out.write("\t\t$(\"#patientFile-for-test-inner\").empty();\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction imageDivFrameOnClick(event){\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.fancybox-nav {\r\n");
      out.write("\t\theight: 80%;\r\n");
      out.write("\t\ttop: 20%;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\t.fancybox-nav span {\r\n");
      out.write("\t\ttop: 40%;\r\n");
      out.write("\t}\r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/pages/clinic/patient/PenVisit/fileBaseItems/PatientFile.jsp(39,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
