/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2018-04-30 10:20:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.clinic.basicInfo.FinanceRegistration;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.io.File;
import com.artonis.core.base.utilClass.ResourceBoundleHolder;

public final class AgentDoctorComboFunc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1513760541684L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/matab/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323245778000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.artonis.core.base.utilClass.ResourceBoundleHolder");
    _jspx_imports_classes.add("java.io.File");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    function cancel_doctorId_Callback(){\r\n");
      out.write("        $(\"#item-modals-doctorId\").dialog('close');\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function success_save_Callback(){\r\n");
      out.write("        $(\"#item-modals-doctorId\").dialog('close');\r\n");
      out.write("        var combobox = $(\"#doctorId_Comb\").data(\"kendoComboBox\");\r\n");
      out.write("        combobox.dataSource.query();\r\n");
      out.write("        combobox.refresh();\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function success_save_doctorId_Callback(){\r\n");
      out.write("        $(\"#item-modals-doctorId\").dialog('close');\r\n");
      out.write("        var combobox = $(\"#doctorId_Comb\").data(\"kendoComboBox\");\r\n");
      out.write("        combobox.dataSource.query();\r\n");
      out.write("        combobox.refresh();\r\n");
      out.write("        combobox.select(0);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function save_doctorId_url(){\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function _doctorId_change(){\r\n");
      out.write("        if($(\"#doctorId_Comb\").val().length==0){\r\n");
      out.write("            $(\"#doctorId\").val(\"\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    function _doctorId_close(e){\r\n");
      out.write("        $(\"#doctorId\").val(e.sender._old);\r\n");
      out.write("        if(typeof(callback_close_doctorId) == \"function\"){\r\n");
      out.write("            callback_close_doctorId(e);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    function _doctorId_dataBound(e){\r\n");
      out.write("        if(typeof(callback_dataBound_doctorId) == \"function\"){\r\n");
      out.write("            callback_dataBound_doctorId(e);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    function _doctorId_open(e){\r\n");
      out.write("        if(typeof(callback_open_doctorId) == \"function\"){\r\n");
      out.write("            callback_open_doctorId(e);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(document).ready(function() {\r\n");
      out.write("        /*var doctorId_val = $(\"#doctorId\");\r\n");
      out.write("\r\n");
      out.write("        doctorId_val.data(\"value\", doctorId_val.val());\r\n");
      out.write("\r\n");
      out.write("        setInterval(function() {\r\n");
      out.write("            var data = doctorId_val.data(\"value\"),\r\n");
      out.write("                    val = doctorId_val.val();\r\n");
      out.write("\r\n");
      out.write("            if (data !== val) {\r\n");
      out.write("                doctorId_val.data(\"value\", val);\r\n");
      out.write("                if(val==\"\"){\r\n");
      out.write("                    $(\"#doctorId_Comb\").data(\"kendoComboBox\").text('');\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }, 100);\r\n");
      out.write("\r\n");
      out.write("        var combobox = $(\"#doctorId_Comb\").data(\"kendoComboBox\");\r\n");
      out.write("        combobox.input.bind(\"keydown\", function(e) {\r\n");
      out.write("            if (e.keyCode == 40) {\r\n");
      out.write("                combobox.open();\r\n");
      out.write("            }\r\n");
      out.write("        });*/\r\n");
      out.write("\r\n");
      out.write("        $(\"#button-doctorId-new\").click(function () {\r\n");
      out.write("            var add = $.get(getBaseUrl()+\"popup/doctorInput\",\r\n");
      out.write("                    function (data) {\r\n");
      out.write("                        $(\"#item-modals-doctorId\").empty();\r\n");
      out.write("                        $(\"#item-modals-doctorId\").append('<div id=\"modals-doctorId\"/>');\r\n");
      out.write("                        $(\"#modals-doctorId\").append(data);\r\n");
      out.write("                        $(\"#item-modals-doctorId\").dialog('open');\r\n");
      out.write("                    }).fail(function (result) {\r\n");
      out.write("                        if (result.status == 401) {\r\n");
      out.write("                            window.location.href = \"\";\r\n");
      out.write("                        }\r\n");
      out.write("                    });\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        $(\"#item-modals-doctorId\").dialog({\r\n");
      out.write("            modal : true,\r\n");
      out.write("            autoOpen: false,\r\n");
      out.write("            maxHeight: true,\r\n");
      out.write("            maxWidth: true,\r\n");
      out.write("            width: 1200,\r\n");
      out.write("            zIndex:10000,\r\n");
      out.write("            close: function( event, ui ) {\r\n");
      out.write("                $(\"#item-modals-doctorId\").empty();\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function _doctorId_select_element(e) {\r\n");
      out.write("        console.log(e);\r\n");
      out.write("        var item = e.item;\r\n");
      out.write("        var dataItem = this.dataItem(e.item.index());\r\n");
      out.write("        $(\"#doctorId\").val(dataItem.id);\r\n");
      out.write("        if(typeof(callback_select_element_doctorId) == \"function\"){\r\n");
      out.write("            callback_select_element_doctorId(dataItem.id);\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function _doctorId_reset(){\r\n");
      out.write("        $(\"#doctorId\").value='';\r\n");
      out.write("        $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\").value='';\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /*window[\"bindToEntityById_after__doctorId_Comb\"] = function () {\r\n");
      out.write("        if ($(\"#doctorId\").val() == \"\") {\r\n");
      out.write("        } else {\r\n");
      out.write("            if (\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isListConstant}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == 'true') {\r\n");
      out.write("                var a2 = $(\"#doctorId\").val();\r\n");
      out.write("                var combobox = $(\"#doctorId_Comb\").data(\"kendoComboBox\");\r\n");
      out.write("                combobox.dataSource.read();\r\n");
      out.write("                combobox.refresh();\r\n");
      out.write("                combobox.select(function (dataItem) {\r\n");
      out.write("                    return dataItem.ComboID == a2;\r\n");
      out.write("                });\r\n");
      out.write("                combobox.value(a2);\r\n");
      out.write("\r\n");
      out.write("            } else {\r\n");
      out.write("                var combobox = $(\"#doctorId_Comb\").data(\"kendoComboBox\");\r\n");
      out.write("\r\n");
      out.write("                var a2 = $(\"#doctorId\").val();\r\n");
      out.write("                var a = $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${value}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\").val();\r\n");
      out.write("                combobox.dataSource.data([\r\n");
      out.write("                    {\"fullName\":a, \"id\":a2}\r\n");
      out.write("                ]);\r\n");
      out.write("                combobox.dataSource.read({\r\n");
      out.write("                    filter: { field: \"id\", operator: \"eq\", value: a2 },\r\n");
      out.write("                    page : 1,\r\n");
      out.write("                    pageSize : 1\r\n");
      out.write("                });\r\n");
      out.write("                combobox.select(combobox.ul.children().eq(0));\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }*/\r\n");
      out.write("\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
