/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2018-04-30 10:09:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ResourceBundle;
import com.artonis.core.base.utilClass.ResourceBoundleHolder;

public final class checkBoxTree_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ResourceBundle");
    _jspx_imports_classes.add("com.artonis.core.base.utilClass.ResourceBoundleHolder");
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.lang.String name;
  private java.lang.String key;
  private java.lang.String loadOnDemand;
  private java.lang.String dataLoaderController;
  private java.lang.String disabled;
  private java.lang.String direction;
  private java.lang.String styleClass;
  private java.lang.String outputResultTag;
  private java.lang.String previousResultTag;
  private java.lang.String filterChkBox;

  public java.lang.String getName() {
    return this.name;
  }

  public void setName(java.lang.String name) {
    this.name = name;
    jspContext.setAttribute("name", name);
  }

  public java.lang.String getKey() {
    return this.key;
  }

  public void setKey(java.lang.String key) {
    this.key = key;
    jspContext.setAttribute("key", key);
  }

  public java.lang.String getLoadOnDemand() {
    return this.loadOnDemand;
  }

  public void setLoadOnDemand(java.lang.String loadOnDemand) {
    this.loadOnDemand = loadOnDemand;
    jspContext.setAttribute("loadOnDemand", loadOnDemand);
  }

  public java.lang.String getDataLoaderController() {
    return this.dataLoaderController;
  }

  public void setDataLoaderController(java.lang.String dataLoaderController) {
    this.dataLoaderController = dataLoaderController;
    jspContext.setAttribute("dataLoaderController", dataLoaderController);
  }

  public java.lang.String getDisabled() {
    return this.disabled;
  }

  public void setDisabled(java.lang.String disabled) {
    this.disabled = disabled;
    jspContext.setAttribute("disabled", disabled);
  }

  public java.lang.String getDirection() {
    return this.direction;
  }

  public void setDirection(java.lang.String direction) {
    this.direction = direction;
    jspContext.setAttribute("direction", direction);
  }

  public java.lang.String getStyleClass() {
    return this.styleClass;
  }

  public void setStyleClass(java.lang.String styleClass) {
    this.styleClass = styleClass;
    jspContext.setAttribute("styleClass", styleClass);
  }

  public java.lang.String getOutputResultTag() {
    return this.outputResultTag;
  }

  public void setOutputResultTag(java.lang.String outputResultTag) {
    this.outputResultTag = outputResultTag;
    jspContext.setAttribute("outputResultTag", outputResultTag);
  }

  public java.lang.String getPreviousResultTag() {
    return this.previousResultTag;
  }

  public void setPreviousResultTag(java.lang.String previousResultTag) {
    this.previousResultTag = previousResultTag;
    jspContext.setAttribute("previousResultTag", previousResultTag);
  }

  public java.lang.String getFilterChkBox() {
    return this.filterChkBox;
  }

  public void setFilterChkBox(java.lang.String filterChkBox) {
    this.filterChkBox = filterChkBox;
    jspContext.setAttribute("filterChkBox", filterChkBox);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getName() != null ) 
      _jspx_page_context.setAttribute("name", getName());
    if( getKey() != null ) 
      _jspx_page_context.setAttribute("key", getKey());
    if( getLoadOnDemand() != null ) 
      _jspx_page_context.setAttribute("loadOnDemand", getLoadOnDemand());
    if( getDataLoaderController() != null ) 
      _jspx_page_context.setAttribute("dataLoaderController", getDataLoaderController());
    if( getDisabled() != null ) 
      _jspx_page_context.setAttribute("disabled", getDisabled());
    if( getDirection() != null ) 
      _jspx_page_context.setAttribute("direction", getDirection());
    if( getStyleClass() != null ) 
      _jspx_page_context.setAttribute("styleClass", getStyleClass());
    if( getOutputResultTag() != null ) 
      _jspx_page_context.setAttribute("outputResultTag", getOutputResultTag());
    if( getPreviousResultTag() != null ) 
      _jspx_page_context.setAttribute("previousResultTag", getPreviousResultTag());
    if( getFilterChkBox() != null ) 
      _jspx_page_context.setAttribute("filterChkBox", getFilterChkBox());

    try {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	boolean isLoadOnDemand=Boolean.valueOf(loadOnDemand);
	if(direction==null || direction.equals(""))
		direction="direction:rtl";
	else
		direction="direction:ltr";
		
	if(styleClass==null ||styleClass.length()==0||styleClass.equals("normal"))
		styleClass="uk-width-4-10";
	else if(styleClass.equals("small"))
		styleClass="uk-width-2-10";
	else if(styleClass.equals("larg"))
		styleClass="uk-width-6-10";
 
      out.write('\r');
      out.write('\n');
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getJspBody() != null)
        getJspBody().invoke(_jspx_sout);
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,getJspContext());
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"container uk-width-6-10\">\r\n");
      out.write("        <div class=\"treeview-back k-rtl\" >\r\n");
      out.write("\r\n");
      out.write("            <div id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\"></div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("    \t$(document).ready(function() {\r\n");
      out.write("     $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").kendoTreeView({\r\n");
      out.write("    \t\tloadOnDemand: ");
      out.print(isLoadOnDemand);
      out.write(",\r\n");
      out.write("            autoBind:true,\r\n");
      out.write("            checkboxes: {\r\n");
      out.write("                checkChildren: true,\r\n");
      out.write("                template: \"<input type='checkbox' id='#= item.id #' value='true' />\"\r\n");
      out.write("            },\r\n");
      out.write("\r\n");
      out.write("            dataSource: {\r\n");
      out.write("                        transport: {\r\n");
      out.write("                        \tparameterMap: function (options) {\r\n");
      out.write("\t\t\t\t                    return JSON.stringify(options);\r\n");
      out.write("\t\t\t\t                },\r\n");
      out.write("                            read: {\r\n");
      out.write("                            \tcontentType: \"application/json\",\r\n");
      out.write("                            \ttype: \"POST\",\r\n");
      out.write("                                url: getBaseUrl() + \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dataLoaderController}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\",\r\n");
      out.write("                                dataType: \"json\"\r\n");
      out.write("                            }\r\n");
      out.write("                        },\r\n");
      out.write("                        schema: {\r\n");
      out.write("                            model: {\r\n");
      out.write("                                id: \"modelID\",\r\n");
      out.write("                                hasChildren: \"hasChild\",\r\n");
      out.write("                                checked: \"checked\"\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("            dataTextField: \"modelCaption\",\r\n");
      out.write("        \tcheckboxes: true,\r\n");
      out.write("        \tselect: onSelect\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\t\tfunction onSelect(e) {\r\n");
      out.write("        \tvar data = $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").data('kendoTreeView').dataItem(e.node);\r\n");
      out.write("\t\t\t/*console.log(data.id);\r\n");
      out.write("        \tconsole.log(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${filterChkBox}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\");*/\r\n");
      out.write("            if(typeof(checkBoxBtnTriggerAftertreeClick) === \"function\"){\r\n");
      out.write("            \tcheckBoxBtnTriggerAftertreeClick(data.id);\r\n");
      out.write("            }\r\n");
      out.write("            if(typeof(checkBoxGridColsBtnTriggerAfterTreeClick) === \"function\"){\r\n");
      out.write("                checkBoxGridColsBtnTriggerAfterTreeClick(data.id);\r\n");
      out.write("            }\r\n");
      out.write("    \t}\r\n");
      out.write("        \r\n");
      out.write("        // function that gathers IDs of checked nodes\r\n");
      out.write("        function checkedNodeIds(nodes, checkedNodes) {\r\n");
      out.write("            for (var i = 0; i < nodes.length; i++) {\r\n");
      out.write("                if (nodes[i].checked) {\r\n");
      out.write("                    checkedNodes.push(nodes[i].id);\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("                if (nodes[i].hasChildren) {\r\n");
      out.write("                    checkedNodeIds(nodes[i].children.view(), checkedNodes);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        function split(e){\r\n");
      out.write("            console.log('split');\r\n");
      out.write("            if($(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${previousResultTag}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").val().length>0){\r\n");
      out.write("               var splitArray=  $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${previousResultTag}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").val().split(',');\r\n");
      out.write("               for(var i= 0;i<splitArray.length;i++){\r\n");
      out.write("                    for(var j=0; j<e.items.length;j++){\r\n");
      out.write("                          if(splitArray[j]== e.items[j].id){\r\n");
      out.write("                              $(\"#\" + e.items[j].id).prop('checked', true);\r\n");
      out.write("                          }\r\n");
      out.write("                    }\r\n");
      out.write("               }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").data(\"kendoTreeView\").dataSource.bind(\"error\", function(e){\r\n");
      out.write("            errorRequestAjax(e);\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("        // show checked node IDs on datasource change\r\n");
      out.write("        $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").data(\"kendoTreeView\").dataSource.bind(\"change\", function(e) {\r\n");
      out.write("//            console.log('change '+ e);\r\n");
      out.write("//            split(e);\r\n");
      out.write("\t\t\t//console.log(e.node.modelID);\r\n");
      out.write("            var checkedNodes = [],\r\n");
      out.write("                treeView = $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${name}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").data(\"kendoTreeView\"),\r\n");
      out.write("                message;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            checkedNodeIds(treeView.dataSource.view(), checkedNodes);\r\n");
      out.write("\r\n");
      out.write("            if (checkedNodes.length > 0) {\r\n");
      out.write("                message = checkedNodes.join(\",\");\r\n");
      out.write("            } else {\r\n");
      out.write("                message = \"\";\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outputResultTag}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").html(message);\r\n");
      out.write("            document.getElementById(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${outputResultTag}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").value=message;\r\n");
      out.write("        });\r\n");
      out.write("    });\r\n");
      out.write("    \r\n");
      out.write("    </script>\t\t\t\r\n");
      out.write("<style scoped>\r\n");
      out.write("        #treeview .k-sprite {\r\n");
      out.write("            background-image: url(\"../../content/web/treeview/coloricons-sprite.png\");\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .rootfolder { background-position: 0 0; }\r\n");
      out.write("        .folder     { background-position: 0 -16px; }\r\n");
      out.write("        .pdf        { background-position: 0 -32px; }\r\n");
      out.write("        .html       { background-position: 0 -48px; }\r\n");
      out.write("        .image      { background-position: 0 -64px; }\r\n");
      out.write("\r\n");
      out.write("        .treeview-back\r\n");
      out.write("        {\r\n");
      out.write("            float: right;\r\n");
      out.write("            margin: 0 0 2em;\r\n");
      out.write("            padding: 20px;\r\n");
      out.write("            -moz-box-shadow: 0 1px 2px rgba(0,0,0,0.45), inset 0 0 30px rgba(0,0,0,0.07);\r\n");
      out.write("            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,0.45), inset 0 0 30px rgba(0,0,0,0.07);\r\n");
      out.write("            box-shadow: 0 1px 2px rgba(0,0,0,0.45), inner 0 0 30px rgba(0,0,0,0.07);\r\n");
      out.write("            -webkit-border-radius: 8px;\r\n");
      out.write("            -moz-border-radius: 8px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        .container\r\n");
      out.write("        {\r\n");
      out.write("            margin: 0 30px;\r\n");
      out.write("            float: right;\r\n");
      out.write("            width: 220px;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        #result\r\n");
      out.write("        {\r\n");
      out.write("            float: right;\r\n");
      out.write("            padding: 10px;\r\n");
      out.write("            -moz-box-shadow: 0 1px 2px rgba(0,0,0,0.45), inset 0 0 30px rgba(0,0,0,0.07);\r\n");
      out.write("            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,0.45), inset 0 0 30px rgba(0,0,0,0.07);\r\n");
      out.write("            box-shadow: 0 1px 2px rgba(0,0,0,0.45), inner 0 0 30px rgba(0,0,0,0.07);\r\n");
      out.write("            -webkit-border-radius: 8px;\r\n");
      out.write("            -moz-border-radius: 8px;\r\n");
      out.write("            border-radius: 8px;\r\n");
      out.write("        }\r\n");
      out.write("    </style>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
