/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2020-02-01 11:47:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.artonis.core.base.utilClass.ResourceBoundleHolder;
import java.util.Map;
import java.util.HashMap;
import java.util.ResourceBundle;
import org.springframework.web.util.UrlPathHelper;
import java.util.List;
import java.util.ArrayList;

public final class formPopup_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1580195752738L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/matab/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323245778000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ResourceBundle");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("org.springframework.web.util.UrlPathHelper");
    _jspx_imports_classes.add("java.util.HashMap");
    _jspx_imports_classes.add("com.artonis.core.base.utilClass.ResourceBoundleHolder");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.lang.String formPopup;
  private java.lang.String popupUrl;
  private java.lang.String itemTabName;
  private java.lang.Boolean disableBackground;
  private java.lang.Boolean disableSaveWithoutCloseButton;
  private java.lang.String styledivLabel;
  private java.lang.String keyLabel;
  private java.lang.String valEndOfPopupUrl;
  private java.lang.String functUrlAppend;

  public java.lang.String getFormPopup() {
    return this.formPopup;
  }

  public void setFormPopup(java.lang.String formPopup) {
    this.formPopup = formPopup;
    jspContext.setAttribute("formPopup", formPopup);
  }

  public java.lang.String getPopupUrl() {
    return this.popupUrl;
  }

  public void setPopupUrl(java.lang.String popupUrl) {
    this.popupUrl = popupUrl;
    jspContext.setAttribute("popupUrl", popupUrl);
  }

  public java.lang.String getItemTabName() {
    return this.itemTabName;
  }

  public void setItemTabName(java.lang.String itemTabName) {
    this.itemTabName = itemTabName;
    jspContext.setAttribute("itemTabName", itemTabName);
  }

  public java.lang.Boolean getDisableBackground() {
    return this.disableBackground;
  }

  public void setDisableBackground(java.lang.Boolean disableBackground) {
    this.disableBackground = disableBackground;
    jspContext.setAttribute("disableBackground", disableBackground);
  }

  public java.lang.Boolean getDisableSaveWithoutCloseButton() {
    return this.disableSaveWithoutCloseButton;
  }

  public void setDisableSaveWithoutCloseButton(java.lang.Boolean disableSaveWithoutCloseButton) {
    this.disableSaveWithoutCloseButton = disableSaveWithoutCloseButton;
    jspContext.setAttribute("disableSaveWithoutCloseButton", disableSaveWithoutCloseButton);
  }

  public java.lang.String getStyledivLabel() {
    return this.styledivLabel;
  }

  public void setStyledivLabel(java.lang.String styledivLabel) {
    this.styledivLabel = styledivLabel;
    jspContext.setAttribute("styledivLabel", styledivLabel);
  }

  public java.lang.String getKeyLabel() {
    return this.keyLabel;
  }

  public void setKeyLabel(java.lang.String keyLabel) {
    this.keyLabel = keyLabel;
    jspContext.setAttribute("keyLabel", keyLabel);
  }

  public java.lang.String getValEndOfPopupUrl() {
    return this.valEndOfPopupUrl;
  }

  public void setValEndOfPopupUrl(java.lang.String valEndOfPopupUrl) {
    this.valEndOfPopupUrl = valEndOfPopupUrl;
    jspContext.setAttribute("valEndOfPopupUrl", valEndOfPopupUrl);
  }

  public java.lang.String getFunctUrlAppend() {
    return this.functUrlAppend;
  }

  public void setFunctUrlAppend(java.lang.String functUrlAppend) {
    this.functUrlAppend = functUrlAppend;
    jspContext.setAttribute("functUrlAppend", functUrlAppend);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getFormPopup() != null ) 
      _jspx_page_context.setAttribute("formPopup", getFormPopup());
    if( getPopupUrl() != null ) 
      _jspx_page_context.setAttribute("popupUrl", getPopupUrl());
    if( getItemTabName() != null ) 
      _jspx_page_context.setAttribute("itemTabName", getItemTabName());
    if( getDisableBackground() != null ) 
      _jspx_page_context.setAttribute("disableBackground", getDisableBackground());
    if( getDisableSaveWithoutCloseButton() != null ) 
      _jspx_page_context.setAttribute("disableSaveWithoutCloseButton", getDisableSaveWithoutCloseButton());
    if( getStyledivLabel() != null ) 
      _jspx_page_context.setAttribute("styledivLabel", getStyledivLabel());
    if( getKeyLabel() != null ) 
      _jspx_page_context.setAttribute("keyLabel", getKeyLabel());
    if( getValEndOfPopupUrl() != null ) 
      _jspx_page_context.setAttribute("valEndOfPopupUrl", getValEndOfPopupUrl());
    if( getFunctUrlAppend() != null ) 
      _jspx_page_context.setAttribute("functUrlAppend", getFunctUrlAppend());

    try {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".mouseOverCursor {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");

	String successMessage=ResourceBoundleHolder.resourceBundle.getString("action.success");
	popupUrl = request.getContextPath() + "" + popupUrl;
	if(disableSaveWithoutCloseButton==null){
		disableSaveWithoutCloseButton=false;
	}
	if(functUrlAppend==null){
		functUrlAppend="null";
	}
	if(valEndOfPopupUrl==null){
		valEndOfPopupUrl="";
	}

      out.write("\r\n");
      out.write("\r\n");
      ((org.apache.jasper.runtime.JspContextWrapper) this.jspContext).syncBeforeInvoke();
      _jspx_sout = null;
      if (getJspBody() != null)
        getJspBody().invoke(_jspx_sout);
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,getJspContext());
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t");
      out.write("\r\n");
      out.write("\t\t<button class=\"uk-button uk-button-success\"   type=\"button\" id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("_popup_button\">\r\n");
      out.write("\t\t\t");
      out.print(ResourceBoundleHolder.resourceBundle.getString(keyLabel));
      out.write("\r\n");
      out.write("\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"uk-width-1-10 left-align\">\r\n");
      out.write("\r\n");
      out.write("\t<div style=\"display:inline;\" id=\"modal-");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tvar originUrl;\r\n");
      out.write("\tvar rowIds = \"\";\r\n");
      out.write("    $(function () {\r\n");
      out.write("        $(\"#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("_popup_button\").click(function () {\r\n");
      out.write("\t\t\trowIds = \"\";\r\n");
      out.write("\t\t\toriginUrl=getBaseUrl();\r\n");
      out.write("            var popUpUrl=\"");
      out.print(popupUrl);
      out.write("\";\r\n");
      out.write("\t\t\tconsole.log(\"--->\"+\"");
      out.print(valEndOfPopupUrl);
      out.write("\");\r\n");
      out.write("\t\t\tif(\"");
      out.print(valEndOfPopupUrl);
      out.write("\".length>0){\r\n");
      out.write("\t\t\t\tpopUpUrl=popUpUrl+$(\"#\"+\"");
      out.print(valEndOfPopupUrl);
      out.write("\").val();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tvar urlAppend=\"\";\r\n");
      out.write("\t\t\tif(");
      out.print(functUrlAppend);
      out.write("!=\"null\" && typeof(");
      out.print(functUrlAppend);
      out.write(") == \"function\"){\r\n");
      out.write("\t\t\t\turlAppend=");
      out.print(functUrlAppend);
      out.write("();\r\n");
      out.write("\t\t\t\turlAppend='/'+urlAppend;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("            var popUpUrl=popUpUrl+urlAppend;\r\n");
      out.write("            $.get(popUpUrl , function (data) {\r\n");
      out.write("                $(\"#modal-\" +\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").empty();\r\n");
      out.write("                var id = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\"  +'_popup';\r\n");
      out.write("                $(\"#modal-\" +\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").append('<div id=\"' + id + '\" class=\"uk-modal\">');\r\n");
      out.write("                $(\"#\" + id).append(data);\r\n");
      out.write("                var modal = new $.UIkit.modal.Modal(\"#\" + id, {modal: false, keyboard: false,bgclose:false});\r\n");
      out.write("\t\t\t\tgetBaseUrl();\r\n");
      out.write("                $(\"#\" + id).on(\r\n");
      out.write("                        {\r\n");
      out.write("                            'uk.modal.hide':function () {\r\n");
      out.write("                                $(\"#modal-\" +\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").empty();\r\n");
      out.write("\t\t\t\t\t\t\t\t$.getJSON(originUrl+'setOriginUrl', function(data){\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t});\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("\t                );\r\n");
      out.write("\r\n");
      out.write("\t\t\t\tif (typeof (callback_popup_load_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write(") == \"function\") {\r\n");
      out.write("\t\t\t\t\tcallback_popup_load_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("();\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t                modal.show();\r\n");
      out.write("\t                \r\n");
      out.write("\t                if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${disableBackground}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" == \"true\"){\r\n");
      out.write("\t                \t$('.uk-modal').css('background','rgba(255, 255, 255, 0)');\r\n");
      out.write("\t                }\r\n");
      out.write("\t\t\t\tvar disableSaveWithoutCloseButton=");
      out.print(disableSaveWithoutCloseButton);
      out.write(";\r\n");
      out.write("\t\t\t\tif(disableSaveWithoutCloseButton==true){\r\n");
      out.write("\t\t\t\t\t$('button[data-action=\"saveWithoutClose\"]', $(\"#\"+id)).show()\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t                \r\n");
      out.write("\t                ");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t$('button[data-action=\"save\"]', $(\"#\" + id)).unbind(\"click\").click(function() {\r\n");
      out.write("\t\t\t\t\tvar tmp=serializeFromFormId(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\");\r\n");
      out.write("\t\t\t\t\tif (typeof (callback_custom_deserialize_popup_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write(") == \"function\") {\r\n");
      out.write("\t\t\t\t\t\tcallback_custom_deserialize_popup_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("(tmp);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tmodal.hide();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t$('button[data-action=\"saveWithoutClose\"]', $(\"#\" + id)).unbind(\"click\").click(function() {\r\n");
      out.write("\t\t\t\t\tvar tmp=serializeFromFormId(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\");\r\n");
      out.write("\t\t\t\t\tvar returnValue=false;\r\n");
      out.write("\t\t\t\t\tif (typeof (callback_custom_deserialize_popup_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write(") == \"function\") {\r\n");
      out.write("\t\t\t\t\t\treturnValue=callback_custom_deserialize_popup_");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("(tmp);\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif(returnValue==true){\r\n");
      out.write("\t\t\t\t\t\talertify.success('");
      out.print(successMessage);
      out.write("');\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t$(\"#\"+\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\").find(\":input\").val('');\r\n");
      out.write("\t\t\t\t\t$(\"#\"+\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${formPopup}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\")[0].reset();\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("\tfunction mouseOver(img) {\r\n");
      out.write("\t\timg.className = 'mouseOverCursor';\r\n");
      out.write("\t}\r\n");
      out.write("\tfunction mouseOut(img) {\r\n");
      out.write("\t\timg.removeAttribute('mouseOverCursor');\r\n");
      out.write("\t}\r\n");
      out.write("</script>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
    }
  }
}
