/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2025-07-12 12:37:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.tag.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.artonis.core.base.utilClass.ResourceBoundleHolder;
import java.util.ResourceBundle;
import org.springframework.web.util.UrlPathHelper;

public final class sortableClinicItem_tag
    extends javax.servlet.jsp.tagext.SimpleTagSupport
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(10);
    _jspx_dependants.put("/WEB-INF/tags/footer.tag", Long.valueOf(1580195770283L));
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1580195752738L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/matab/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323245778000L));
    _jspx_dependants.put("/WEB-INF/tags/buttonPermission.tag", Long.valueOf(1580195815571L));
    _jspx_dependants.put("/WEB-INF/tags/dialogAlert.tag", Long.valueOf(1580195811967L));
    _jspx_dependants.put("/WEB-INF/tags/optiion.tag", Long.valueOf(1580195964669L));
    _jspx_dependants.put("/WEB-INF/kendo-taglibs.tld", Long.valueOf(1580195833241L));
    _jspx_dependants.put("/WEB-INF/tags/testBox.tag", Long.valueOf(1580195926628L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/matab/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/fn.tld", Long.valueOf(1323245778000L));
    _jspx_dependants.put("/WEB-INF/tags/dialogConfirm.tag", Long.valueOf(1580195821308L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ResourceBundle");
    _jspx_imports_classes.add("org.springframework.web.util.UrlPathHelper");
    _jspx_imports_classes.add("com.artonis.core.base.utilClass.ResourceBoundleHolder");
  }

  private javax.servlet.jsp.JspContext jspContext;
  private java.io.Writer _jspx_sout;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public void setJspContext(javax.servlet.jsp.JspContext ctx) {
    super.setJspContext(ctx);
    java.util.ArrayList _jspx_nested = null;
    java.util.ArrayList _jspx_at_begin = null;
    java.util.ArrayList _jspx_at_end = null;
    this.jspContext = new org.apache.jasper.runtime.JspContextWrapper(this, ctx, _jspx_nested, _jspx_at_begin, _jspx_at_end, null);
  }

  public javax.servlet.jsp.JspContext getJspContext() {
    return this.jspContext;
  }
  private java.lang.String categoryListPlaceHolder;
  private java.lang.String categoryNameItem;
  private java.lang.String operationAllUrl;
  private java.lang.String saveUrl;

  public java.lang.String getCategoryListPlaceHolder() {
    return this.categoryListPlaceHolder;
  }

  public void setCategoryListPlaceHolder(java.lang.String categoryListPlaceHolder) {
    this.categoryListPlaceHolder = categoryListPlaceHolder;
    jspContext.setAttribute("categoryListPlaceHolder", categoryListPlaceHolder);
  }

  public java.lang.String getCategoryNameItem() {
    return this.categoryNameItem;
  }

  public void setCategoryNameItem(java.lang.String categoryNameItem) {
    this.categoryNameItem = categoryNameItem;
    jspContext.setAttribute("categoryNameItem", categoryNameItem);
  }

  public java.lang.String getOperationAllUrl() {
    return this.operationAllUrl;
  }

  public void setOperationAllUrl(java.lang.String operationAllUrl) {
    this.operationAllUrl = operationAllUrl;
    jspContext.setAttribute("operationAllUrl", operationAllUrl);
  }

  public java.lang.String getSaveUrl() {
    return this.saveUrl;
  }

  public void setSaveUrl(java.lang.String saveUrl) {
    this.saveUrl = saveUrl;
    jspContext.setAttribute("saveUrl", saveUrl);
  }

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    return _jsp_instancemanager;
  }

  private void _jspInit(javax.servlet.ServletConfig config) {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(config);
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(config.getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(config);
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void doTag() throws javax.servlet.jsp.JspException, java.io.IOException {
    javax.servlet.jsp.PageContext _jspx_page_context = (javax.servlet.jsp.PageContext)jspContext;
    javax.servlet.http.HttpServletRequest request = (javax.servlet.http.HttpServletRequest) _jspx_page_context.getRequest();
    javax.servlet.http.HttpServletResponse response = (javax.servlet.http.HttpServletResponse) _jspx_page_context.getResponse();
    javax.servlet.http.HttpSession session = _jspx_page_context.getSession();
    javax.servlet.ServletContext application = _jspx_page_context.getServletContext();
    javax.servlet.ServletConfig config = _jspx_page_context.getServletConfig();
    javax.servlet.jsp.JspWriter out = jspContext.getOut();
    _jspInit(config);
    jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,jspContext);
    if( getCategoryListPlaceHolder() != null ) 
      _jspx_page_context.setAttribute("categoryListPlaceHolder", getCategoryListPlaceHolder());
    if( getCategoryNameItem() != null ) 
      _jspx_page_context.setAttribute("categoryNameItem", getCategoryNameItem());
    if( getOperationAllUrl() != null ) 
      _jspx_page_context.setAttribute("operationAllUrl", getOperationAllUrl());
    if( getSaveUrl() != null ) 
      _jspx_page_context.setAttribute("saveUrl", getSaveUrl());

    try {
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	ResourceBundle resource = ResourceBundle.getBundle("application_fa");
	String basePath = new UrlPathHelper().getOriginatingRequestUri(request);
	request.setAttribute("basePath", basePath);
 
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <input name=\"loadedId\" type=\"hidden\" id=\"loadedId\" />\r\n");
      out.write("\r\n");
      out.write("<div class=\"body-header\">\r\n");
      out.write("\t<ul class=\"uk-breadcrumb uk-h3\" id=\"breadcrumb\">\r\n");
      out.write("\t\t<li id=\"breadcrumb-main-section\"><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("</span>\r\n");
      out.write("\t\t</li>\r\n");
      out.write("\t</ul>\r\n");
      out.write("\t<div id=\"header-toolbar\">\r\n");
      out.write("\t\t");
      if (_jspx_meth_base_005fbuttonPermission_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div align=\"left\" style=\" display: inline-block; width: 100%; direction: ltr; \">\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    <div id=\"leftDiv\" style=\"display: inline-block;width: 40%;vertical-align: top;;border:solid 1px #ccc;border-radius: 5px;overflow: auto;margin-left: 20px\">\r\n");
      out.write("        <div id=\"nameCategoryList\" style=\"direction: ltr;width: 100%;\">\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("            <input id=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryNameItem}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\" placeholder=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryListPlaceHolder}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\"/>\r\n");
      out.write("            <button id=\"addCategory\">\r\n");
      out.write("                +\r\n");
      out.write("            </button>\r\n");
      out.write("            <ul class=\"list\">\r\n");
      out.write("            </ul>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"rightDiv\"style=\"display: inline-block;width: 50%;border:solid 1px #ccc;border-radius: 5px;overflow: auto;margin-left: 70px\">\r\n");
      out.write("        ");
      out.write("\r\n");
      out.write("        \r\n");
      out.write("        ");
      if (_jspx_meth_base_005foptiion_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("        <div id=\"itemList\" style=\"direction: ltr;width: 100%;\">\r\n");
      out.write("            <input class=\"search\" placeholder=\"Search\" />\r\n");
      out.write("            <button class=\"sort\" data-sort=\"item\" id=\"sortItem\">\r\n");
      out.write("                Sort by name\r\n");
      out.write("            </button>\r\n");
      out.write("            <ul class=\"list\">\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      if (_jspx_meth_base_005fdialogConfirm_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_base_005fdialogConfirm_005f1(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_base_005fdialogAlert_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"editNameCategory\" class=\"uk-container uk-container-center my-uk-container\" style=\"display:none;direction: rtl;\">\r\n");
      out.write("    <div class=\"uk-grid uk-grid-preserve\">\r\n");
      out.write("        ");
      if (_jspx_meth_base_005ftestBox_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      if (_jspx_meth_base_005ffooter_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("var currentNameCategorySelect;\r\n");
      out.write("$('.ui-multiselect-all')[0].parentElement.remove();\r\n");
      out.write("$(\"#editNameCategory\").dialog({\r\n");
      out.write("    autoOpen:false,\r\n");
      out.write("    show:{\r\n");
      out.write("        effect:\"slide\",\r\n");
      out.write("        duration:300\r\n");
      out.write("    },\r\n");
      out.write("    hide:{\r\n");
      out.write("        effect:\"slide\",\r\n");
      out.write("        duration:300\r\n");
      out.write("    },\r\n");
      out.write("//    height:800,\r\n");
      out.write("    width:800,\r\n");
      out.write("    modal:true,\r\n");
      out.write("    buttons:{\r\n");
      out.write("        \"apply\":function () {\r\n");
      out.write("\r\n");
      out.write("            var oldValue=$(this).data('contents').parents()[1].childNodes[1].innerText;\r\n");
      out.write("//            $(this).data('contents').parents()[1].childNodes[1].innerText=$(\"#nameCategory\").val();\r\n");
      out.write("            if(nameCategoryList.get('nameCategory', $(\"#nameCategory\").val()).length>0){\r\n");
      out.write("                $(this).dialog(\"close\");\r\n");
      out.write("                $(\"#dialogAlertDuplicatItem\").dialog(\"open\");\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("            var item=nameCategoryList.get('nameCategory', oldValue)[0];\r\n");
      out.write("            item.values({\r\n");
      out.write("                nameCategory:$(\"#nameCategory\").val()\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("//            console.log($(this).data('contents'));\r\n");
      out.write("            var counter=0;\r\n");
      out.write("            Object.keys(nameCategoryMap).forEach(function(key) {\r\n");
      out.write("                counter++;\r\n");
      out.write("                if(key==oldValue){\r\n");
      out.write("\r\n");
      out.write("                    nameCategoryMap[$(\"#nameCategory\").val()] = nameCategoryMap[oldValue];\r\n");
      out.write("                    delete nameCategoryMap[key];\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("            if(counter>0){\r\n");
      out.write("                newSortCategory();\r\n");
      out.write("            }\r\n");
      out.write("            if(currentNameCategorySelect==oldValue){\r\n");
      out.write("                currentNameCategorySelect=$(\"#nameCategory\").val();\r\n");
      out.write("            }\r\n");
      out.write("            $(\"#nameCategory\").val(\"\");\r\n");
      out.write("            console.log(nameCategoryMap);\r\n");
      out.write("            $(this).dialog(\"close\");\r\n");
      out.write("        },\r\n");
      out.write("        \"cancel\":function () {\r\n");
      out.write("\r\n");
      out.write("            $(this).dialog(\"close\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("    $(\"#leftDiv\").css(\"max-height\",$(window).height()-($(\".body-header\").height()*2)) ;\r\n");
      out.write("    $(\"#rightDiv\").css(\"max-height\",$(window).height()-($(\".body-header\").height()*2)) ;\r\n");
      out.write("    var $widget = $(\"select\").multiselect(),\r\n");
      out.write("            state = false;\r\n");
      out.write("    $widget.multiselect('disable');\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    var options = {\r\n");
      out.write("        valueNames: [ 'item' ],\r\n");
      out.write("        page:1000,\r\n");
      out.write("        item: '<li style=\"display: inline-block;width: 95%\"><span  class=\"sort-handle\">&#8225;</span><h3 style=\"display: inline-block;\" class=\"item\"></h3><p hidden class=\"id\"></p><a style=\"float: right;\"  href=\"#\"><img onclick=\"deleteLiItem($(this))\" src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" alt=\"\"/></a></li>'\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    var optionsNameCategory = {\r\n");
      out.write("        valueNames: [ 'nameCategory' ],\r\n");
      out.write("//        item: '<li style=\"display: inline-block;width: 95%\"><span  class=\"sort-handle\">&#8225;</span><h3 style=\"display: inline-block;\" class=\"nameCategory\"></h3><span   style=\"float: right;\"><a  href=\"#\"><img onclick=\"deleteLi()\"  alt=\"\"/></a></span></li>'\r\n");
      out.write("        item: '<li style=\"display: inline-block;width: 95%\"><span  class=\"sort-handle\">&#8225;</span><h3 style=\"display: inline-block;\" class=\"nameCategory\"></h3><a style=\"float: right;margin-left:10px;\" href=\"#\"><span onclick=\"editClick($(this))\" style=\"float:right\" class=\"k-icon k-edit\"></span></a><a style=\"float: right;\"  href=\"#\"><img onclick=\"deleteLiNameCategory($(this))\" src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" alt=\"\"/></a></li>'\r\n");
      out.write("    };\r\n");
      out.write("//\r\n");
      out.write("    var nameCategoryList = new List('nameCategoryList', optionsNameCategory);\r\n");
      out.write("\r\n");
      out.write("    var itemList = new List('itemList', options);\r\n");
      out.write("\r\n");
      out.write("    var nameCategoryMap={};\r\n");
      out.write("\r\n");
      out.write("    $('.list').selectable({\r\n");
      out.write("        cancel: '.sort-handle,img,span',\r\n");
      out.write("        selected: function( event, ui ) {\r\n");
      out.write("            console.log(event,ui);\r\n");
      out.write("            if(ui.selected.parentElement.parentElement.id==\"nameCategoryList\"){\r\n");
      out.write("                if(state==false){\r\n");
      out.write("                    state=true;\r\n");
      out.write("                    $widget.multiselect('enable');\r\n");
      out.write("                }\r\n");
      out.write("                if(currentNameCategorySelect!=ui.selected.childNodes[1].innerText){\r\n");
      out.write("                    itemList.clear();\r\n");
      out.write("                    var labTestCheckedList=$(\"#orders_customized\").multiselect(\"widget\").find(\":checkbox:checked\");\r\n");
      out.write("                    for(var i=0;i<labTestCheckedList.length;i++){\r\n");
      out.write("                        $(\"#orders_customized\").multiselect(\"widget\").find(\":checkbox[value='\" +labTestCheckedList[i].value + \"']\").attr(\"checked\", \"false\");\r\n");
      out.write("                        $(\"#orders_customized option[value='\" +labTestCheckedList[i].value  + \"']\").attr(\"selected\", false);\r\n");
      out.write("//                        $(\"#orders_customized\").multiselect(\"refresh\");\r\n");
      out.write("\r\n");
      out.write("                    }\r\n");
      out.write("                    currentNameCategorySelect=ui.selected.childNodes[1].innerText;\r\n");
      out.write("\r\n");
      out.write("                    //load list item\r\n");
      out.write("                    var labTestListOfNameCategory=nameCategoryMap[currentNameCategorySelect];\r\n");
      out.write("                    if(labTestListOfNameCategory!=undefined){\r\n");
      out.write("                        for(var j=0;j<labTestListOfNameCategory.length;j++){\r\n");
      out.write("                            var labTestMap=labTestListOfNameCategory[j];\r\n");
      out.write("                            if(labTestMap['value']!=undefined){\r\n");
      out.write("                                itemList.add({ item: labTestMap['value'].trim() , id: labTestMap['id'].trim() });\r\n");
      out.write("                                $(\"#orders_customized\").multiselect(\"widget\").find(\":checkbox[value='\" +labTestMap['id']+ \"']\").attr(\"checked\", \"true\");\r\n");
      out.write("                                $(\"#orders_customized option[value='\" +labTestMap['id'] + \"']\").attr(\"selected\", true);\r\n");
      out.write("                            }\r\n");
      out.write("\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                    $(\"#orders_customized\").multiselect(\"refresh\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    }).sortable({\r\n");
      out.write("                items: \"> li\",\r\n");
      out.write("                handle: '.sort-handle',\r\n");
      out.write("                helper: function(e, item) {\r\n");
      out.write("                    if ( ! item.hasClass('ui-selected') ) {\r\n");
      out.write("                        item.parent().children('.ui-selected').removeClass('ui-selected');\r\n");
      out.write("                        item.addClass('ui-selected');\r\n");
      out.write("                    }\r\n");
      out.write("\r\n");
      out.write("                    var selected = item.parent().children('.ui-selected').clone();\r\n");
      out.write("                    item.data('multidrag', selected).siblings('.ui-selected').remove();\r\n");
      out.write("\r\n");
      out.write("                    return $('<li/>').append(selected);\r\n");
      out.write("                },\r\n");
      out.write("                stop: function(e, ui) {\r\n");
      out.write("                    var selected = ui.item.data('multidrag');\r\n");
      out.write("\r\n");
      out.write("                    if(ui.item[0].parentElement.parentElement.id==\"nameCategoryList\"){\r\n");
      out.write("                        newSortCategory();\r\n");
      out.write("                    }else{\r\n");
      out.write("                        newSortItems();\r\n");
      out.write("                    }\r\n");
      out.write("                    ui.item.after(selected);\r\n");
      out.write("                    ui.item.remove();\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("\r\n");
      out.write("jQuery.ajax({\r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("    url:basePath + '/load/',\r\n");
      out.write("    type:\"GET\",\r\n");
      out.write("    dataType:\"json\",\r\n");
      out.write("    contentType:\"application/json; charset=utf-8\",\r\n");
      out.write("    success:function (data) {\r\n");
      out.write("//        nameCategoryMap=data;\r\n");
      out.write("        console.log(data);\r\n");
      out.write("\r\n");
      out.write("        for(var i=0;i< data.length;i++){\r\n");
      out.write("            var labTestListOfNameCategoryNew=[];\r\n");
      out.write("            for(var j=0;j<data[i].list.length;j++){\r\n");
      out.write("               var labTestIdtestMap={};\r\n");
      out.write("               if(j==data[i].list.length-1){\r\n");
      out.write("                   labTestIdtestMap[\"order\"]=parseInt(data[i].list[j].order);\r\n");
      out.write("                   labTestListOfNameCategoryNew[j]=labTestIdtestMap;\r\n");
      out.write("               }else{\r\n");
      out.write("                   labTestIdtestMap[\"id\"]=data[i].list[j].id;\r\n");
      out.write("                   labTestIdtestMap[\"value\"]=data[i].list[j].value;\r\n");
      out.write("                   labTestListOfNameCategoryNew[j]=labTestIdtestMap;\r\n");
      out.write("               }\r\n");
      out.write("           }\r\n");
      out.write("           nameCategoryMap[data[i].string]=labTestListOfNameCategoryNew;\r\n");
      out.write("\r\n");
      out.write("            nameCategoryList.add({ nameCategory: data[i].string });\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        console.log(nameCategoryMap);\r\n");
      out.write("    },\r\n");
      out.write("    error:function(result){\r\n");
      out.write("        if(result.status==401){\r\n");
      out.write("            window.location.href=getBaseUrl();\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("});\r\n");
      out.write("  /*  $.getJSON(basePath + '/load/', function(data) {\r\n");
      out.write("        nameCategoryMap=data;\r\n");
      out.write("          console.log(data);\r\n");
      out.write("\r\n");
      out.write("        $.each(data, function (key, val) {\r\n");
      out.write("            if(currentNameCategorySelect==undefined){\r\n");
      out.write("//                currentNameCategorySelect=key;\r\n");
      out.write("            }\r\n");
      out.write("            nameCategoryList.add({ nameCategory: key });\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("*/\r\n");
      out.write("    $(\"#sortItem\").on('click', function (event) {\r\n");
      out.write("        newSortItems();\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function deleteLiNameCategory(e){\r\n");
      out.write("\r\n");
      out.write("        $(\"#dialogDeleteNameCategory\").data('contents',e).dialog(\"open\");\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function deleteLiItem(e){\r\n");
      out.write("\r\n");
      out.write("        $(\"#dialogDeleteItem\").data('contents',e).dialog(\"open\");\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function editClick(e){\r\n");
      out.write("        console.log(e);\r\n");
      out.write("        $(\"#nameCategory\").val(e.parents()[1].childNodes[1].innerText);\r\n");
      out.write("        $(\"#editNameCategory\").data('contents',e).dialog(\"open\");\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function yesDeleteNameCategory(e){\r\n");
      out.write("        nameCategoryList.remove(\"nameCategory\",e.data('contents').parents()[1].childNodes[1].innerText);\r\n");
      out.write("\r\n");
      out.write("        var newNameCategoryMap={};\r\n");
      out.write("        $.each(nameCategoryMap, function (key, val) {\r\n");
      out.write("            if(key!=e.data('contents').parents()[1].childNodes[1].innerText){\r\n");
      out.write("                newNameCategoryMap[key]=val;\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        nameCategoryMap=newNameCategoryMap;\r\n");
      out.write("        console.log(nameCategoryMap);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function yesDeleteItem(e){\r\n");
      out.write("        var id=e.data('contents').parents()[1].childNodes[2].innerText;\r\n");
      out.write("        itemList.remove(\"id\",id);\r\n");
      out.write("        removeItem(id);\r\n");
      out.write("\r\n");
      out.write("        $(\"#orders_customized\").multiselect(\"widget\").find(\":checkbox[value='\" +id + \"']\").attr(\"checked\", \"false\");\r\n");
      out.write("        $(\"#orders_customized option[value='\" +id  + \"']\").attr(\"selected\", false);\r\n");
      out.write("        $(\"#orders_customized\").multiselect(\"refresh\");\r\n");
      out.write("        console.log(nameCategoryMap);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    $(\"#addCategory\").on('click', function (event) {\r\n");
      out.write("        if(nameCategoryList.get('nameCategory', $('#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryNameItem}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("').val()).length==0){\r\n");
      out.write("            nameCategoryList.add({ nameCategory: $('#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryNameItem}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("').val() });\r\n");
      out.write("        }else{\r\n");
      out.write("            $(\"#dialogAlertDuplicatItem\").dialog(\"open\");\r\n");
      out.write("        }\r\n");
      out.write("        $('#");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${categoryNameItem}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("').val('');\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("    function SelectSelectableElement (selectableContainer, elementsToSelect)\r\n");
      out.write("    {\r\n");
      out.write("        // add unselecting class to all elements in the styleboard canvas except the ones to select\r\n");
      out.write("        $(\".ui-selected\", selectableContainer).not(elementsToSelect).removeClass(\"ui-selected\").addClass(\"ui-unselecting\");\r\n");
      out.write("\r\n");
      out.write("        // add ui-selecting class to the elements to select\r\n");
      out.write("        $(elementsToSelect).not(\".ui-selected\").addClass(\"ui-selecting\");\r\n");
      out.write("\r\n");
      out.write("        // trigger the mouse stop event (this will select all .ui-selecting elements, and deselect all .ui-unselecting elements)\r\n");
      out.write("        selectableContainer.data(\"ui-selectable\")._mouseStop(null);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function callBack_after_full_date_orders_customized(){\r\n");
      out.write("//        $(\"#leftDiv\").height($(\"#rightDiv\").height());\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function newSortItems(){\r\n");
      out.write("        var labTestListOfNameCategoryNew=[];\r\n");
      out.write("        for(var i=0;i< $('.list')[1].childNodes.length;i++){\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            var labTestIdtestMap={};\r\n");
      out.write("            labTestIdtestMap[\"id\"]=$('.list')[1].childNodes[i].childNodes[2].innerText;\r\n");
      out.write("            labTestIdtestMap[\"value\"]=$('.list')[1].childNodes[i].childNodes[1].innerText;\r\n");
      out.write("            labTestListOfNameCategoryNew[i]=labTestIdtestMap;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("        nameCategoryMap[currentNameCategorySelect]=labTestListOfNameCategoryNew;\r\n");
      out.write("        newSortCategory();\r\n");
      out.write("        console.log(nameCategoryMap);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    function newSortCategory(){\r\n");
      out.write("        var nameCategoryMapNew={};\r\n");
      out.write("        for(var i=0;i<$('.list')[0].childNodes.length;i++){\r\n");
      out.write("            var itemText=$('.list')[0].childNodes[i].childNodes[1].innerText;\r\n");
      out.write("            if(nameCategoryMap[itemText]!=undefined){\r\n");
      out.write("                if(nameCategoryMap[itemText][nameCategoryMap[itemText].length-1]['order']==undefined){\r\n");
      out.write("                    var labTestCategoryOrder={};\r\n");
      out.write("                    labTestCategoryOrder[\"order\"]=i+1\r\n");
      out.write("                    nameCategoryMap[itemText][nameCategoryMap[itemText].length]=labTestCategoryOrder;\r\n");
      out.write("                    nameCategoryMapNew[itemText]=nameCategoryMap[itemText];\r\n");
      out.write("                }else{\r\n");
      out.write("                    nameCategoryMap[itemText][nameCategoryMap[itemText].length-1]['order']=i+1;\r\n");
      out.write("                    nameCategoryMapNew[itemText]=nameCategoryMap[itemText];\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        nameCategoryMap=nameCategoryMapNew;\r\n");
      out.write("\r\n");
      out.write("        console.log(nameCategoryMap);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function addItem(id,value){\r\n");
      out.write("\r\n");
      out.write("        var isDouplicate=false;\r\n");
      out.write("        $.each(nameCategoryMap, function (key, val) {\r\n");
      out.write("\r\n");
      out.write("            for(var p=0;p<val.length;p++){\r\n");
      out.write("                if(val[p].id==id){\r\n");
      out.write("\r\n");
      out.write("//                    $(\"#orders_customized\").multiselect(\"widget\").find(\":checkbox[value='\" +id + \"']\").attr(\"checked\", \"false\");\r\n");
      out.write("//                    $(\"#orders_customized option[value='\" +id  + \"']\").attr(\"selected\", false);\r\n");
      out.write("//                    $(\"#orders_customized\").multiselect(\"refresh\");\r\n");
      out.write("                    isDouplicate=true;\r\n");
      out.write("\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("        if(isDouplicate==true){\r\n");
      out.write("            return false;\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("        itemList.add({ item: value,id:id });\r\n");
      out.write("        if(nameCategoryMap[currentNameCategorySelect]==undefined){\r\n");
      out.write("            var labTestListOfNameCategory=[];\r\n");
      out.write("\r\n");
      out.write("            var labTestIdtestMap={};\r\n");
      out.write("            labTestIdtestMap[\"id\"]=id;\r\n");
      out.write("            labTestIdtestMap[\"value\"]=value;\r\n");
      out.write("            labTestListOfNameCategory[0]=labTestIdtestMap;\r\n");
      out.write("            nameCategoryMap[currentNameCategorySelect]=labTestListOfNameCategory;\r\n");
      out.write("\r\n");
      out.write("        }else{\r\n");
      out.write("            var labTestListOfNameCategory=nameCategoryMap[currentNameCategorySelect];\r\n");
      out.write("\r\n");
      out.write("            var labTestIdtestMap={};\r\n");
      out.write("            labTestIdtestMap[\"id\"]=id;\r\n");
      out.write("            labTestIdtestMap[\"value\"]=value;\r\n");
      out.write("            labTestListOfNameCategory[labTestListOfNameCategory.length]=labTestIdtestMap;\r\n");
      out.write("            nameCategoryMap[currentNameCategorySelect]=labTestListOfNameCategory;\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function loadItem(id,value){\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    function removeItem(id){\r\n");
      out.write("        var labTestListOfNameCategory=nameCategoryMap[currentNameCategorySelect];\r\n");
      out.write("        for(var i=0;i<labTestListOfNameCategory.length;i++){\r\n");
      out.write("            var labTestIdtestMap=labTestListOfNameCategory[i];\r\n");
      out.write("            if(labTestIdtestMap[\"id\"]==id){\r\n");
      out.write("                labTestListOfNameCategory.splice(i, 1);\r\n");
      out.write("            }else{\r\n");
      out.write("\r\n");
      out.write("                labTestListOfNameCategory[i]=labTestIdtestMap;\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        nameCategoryMap[currentNameCategorySelect]=labTestListOfNameCategory;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("function checkAllCustomizeEvent(event, ui){\r\n");
      out.write("    var falseReturnValue=false;\r\n");
      out.write("    for(var i=0;i<event.target.length;i++){\r\n");
      out.write("        if(itemList.get(\"item\", event.target[i].innerText ).length==0){\r\n");
      out.write("            var isAdded=addItem(event.target[i].value,event.target[i].innerText.trim());\r\n");
      out.write("            if(isAdded==false){\r\n");
      out.write("                $(\"#dialogAlertDuplicatItem\").dialog(\"open\");\r\n");
      out.write("                event.preventDefault();\r\n");
      out.write("                return;\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    console.log(nameCategoryMap);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function clickCustomizeEvent(event,ui){\r\n");
      out.write("    var labtestname=$('#orders_customized option[value=\"' + ui.value + '\"]').html();\r\n");
      out.write("    if(ui.checked==true){\r\n");
      out.write("         var isAdded=addItem(ui.value,labtestname);\r\n");
      out.write("        if(isAdded==false){\r\n");
      out.write("            $(\"#dialogAlertDuplicatItem\").dialog(\"open\");\r\n");
      out.write("            event.preventDefault();\r\n");
      out.write("            return;\r\n");
      out.write("        }\r\n");
      out.write("    }else{\r\n");
      out.write("        itemList.remove(\"id\",ui.value);\r\n");
      out.write("        removeItem(ui.value);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    console.log(nameCategoryMap);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function beforeCloseCustomizeEvent(event,ui){\r\n");
      out.write("    $(\"button\")[2].childNodes[1].innerText=\"\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function optgrouptoggleCustomizeEvent(event,ui){\r\n");
      out.write("    if(ui.checked==true){\r\n");
      out.write("        var falseReturnValue=false;\r\n");
      out.write("        for(var i=0;i<ui.inputs.length;i++){\r\n");
      out.write("            if(itemList.get(\"item\", ui.inputs[i].labels[0].innerText ).length==0){\r\n");
      out.write("//                itemList.add({ item: ui.inputs[i].labels[0].innerText.trim(),id:ui.inputs[0].value });\r\n");
      out.write("                var isAdded=addItem(ui.inputs[i].value,ui.inputs[i].labels[0].innerText.trim());\r\n");
      out.write("                if(isAdded==false){\r\n");
      out.write("                    falseReturnValue=true;\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("        if(falseReturnValue==true){\r\n");
      out.write("            $(\"#dialogAlertDuplicatItem\").dialog(\"open\");\r\n");
      out.write("        }\r\n");
      out.write("    }else{\r\n");
      out.write("        for(var j=0;j<ui.inputs.length;j++){\r\n");
      out.write("\r\n");
      out.write("            itemList.remove(\"id\", ui.inputs[j].value);\r\n");
      out.write("            removeItem(ui.inputs[j].value);\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("    }\r\n");
      out.write("    console.log(nameCategoryMap)\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function unCheckAllCustomizeEvent(event,ui){\r\n");
      out.write("\r\n");
      out.write("    itemList.clear();\r\n");
      out.write("    var labTestListOfNameCategory=[];\r\n");
      out.write("    nameCategoryMap[currentNameCategorySelect]=labTestListOfNameCategory;\r\n");
      out.write("    console.log(nameCategoryMap);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(\"#userView-save\").click(function(){\r\n");
      out.write("\r\n");
      out.write("                jQuery.ajax({\r\n");
      out.write("                    ");
      out.write("\r\n");
      out.write("                    url:\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" +\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${saveUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
      out.write("\",\r\n");
      out.write("                    type:\"POST\",\r\n");
      out.write("                    data:JSON.stringify(nameCategoryMap),\r\n");
      out.write("                    dataType:\"json\",\r\n");
      out.write("                    contentType:\"application/json; charset=utf-8\",\r\n");
      out.write("                    success:function (result) {\r\n");
      out.write("                        if (result.state == \"error\") {\r\n");
      out.write("                            for (var i = 0; i < result.errors.length; i++) {\r\n");
      out.write("                                if ($(\"label[for='\" + result.errors[i].Field + \"']\").text().length > 0) {\r\n");
      out.write("                                    alertify.error($(\"label[for='\" + result.errors[i].Field + \"']\").text() + \":  \" + result.errors[i].Message);\r\n");
      out.write("                                } else {\r\n");
      out.write("                                    alertify.error(result.errors[i].Field + \":  \" + result.errors[i].Message);\r\n");
      out.write("\r\n");
      out.write("                                }\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                        if (result.state == \"success\") {\r\n");
      out.write("                            alertify.success(result.message);\r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("                        }\r\n");
      out.write("                    },\r\n");
      out.write("                    error:function(result){\r\n");
      out.write("                        if(result.status==401){\r\n");
      out.write("                            window.location.href=getBaseUrl();\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("\t.uk-width-2-5, .uk-width-4-10 {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t}\r\n");
      out.write("\t.ms-container {\r\n");
      out.write("\t\tbackground: transparent url('../../../resources/js/img/switch.png') no-repeat 50% 50%;\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\tpadding-top: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.uk-width-1-10 {\r\n");
      out.write("\t\twidth: 100%;\r\n");
      out.write("\t\theight: 5%;\r\n");
      out.write("\t\ttext-align: -webkit-center;\r\n");
      out.write("\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t.ms-list{\r\n");
      out.write("\t\tdirection: ltr;\r\n");
      out.write("\t}\r\n");
      out.write("\t.custom-header{\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t\t#body-content{\r\n");
      out.write("\t\tbackground: -webkit-gradient(linear, left top, left bottom, color-stop(0%,#f2f5f6), color-stop(37%,#e3eaed), color-stop(100%,#c8d7dc)); /* Chrome,Safari4+ */\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    .list {\r\n");
      out.write("        font-family:sans-serif;\r\n");
      out.write("        margin:0;\r\n");
      out.write("        padding:20px 0 0;\r\n");
      out.write("    }\r\n");
      out.write("    .list > li {\r\n");
      out.write("        display:block;\r\n");
      out.write("        background-color: #eee;\r\n");
      out.write("        padding:10px;\r\n");
      out.write("        box-shadow: inset 0 1px 0 #fff;\r\n");
      out.write("    }\r\n");
      out.write("    .avatar {\r\n");
      out.write("        max-width: 150px;\r\n");
      out.write("    }\r\n");
      out.write("    img {\r\n");
      out.write("        max-width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("    h3 {\r\n");
      out.write("        font-size: 16px;\r\n");
      out.write("        margin:0 0 0.3rem;\r\n");
      out.write("        font-weight: normal;\r\n");
      out.write("        font-weight:bold;\r\n");
      out.write("    }\r\n");
      out.write("    p {\r\n");
      out.write("        margin:0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    input {\r\n");
      out.write("        border:solid 1px #ccc;\r\n");
      out.write("        border-radius: 5px;\r\n");
      out.write("        padding:7px 14px;\r\n");
      out.write("        /*margin-bottom:10px*/\r\n");
      out.write("    }\r\n");
      out.write("    input:focus {\r\n");
      out.write("        outline:none;\r\n");
      out.write("        border-color:#aaa;\r\n");
      out.write("    }\r\n");
      out.write("    .sort {\r\n");
      out.write("        padding:8px 30px;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        border:none;\r\n");
      out.write("        display:inline-block;\r\n");
      out.write("        color:#fff;\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        background-color: #28a8e0;\r\n");
      out.write("        height:30px;\r\n");
      out.write("    }\r\n");
      out.write("    .sort:hover {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        background-color:#1b8aba;\r\n");
      out.write("    }\r\n");
      out.write("    .sort:focus {\r\n");
      out.write("        outline:none;\r\n");
      out.write("    }\r\n");
      out.write("    .sort:after {\r\n");
      out.write("        width: 0;\r\n");
      out.write("        height: 0;\r\n");
      out.write("        border-left: 5px solid transparent;\r\n");
      out.write("        border-right: 5px solid transparent;\r\n");
      out.write("        border-bottom: 5px solid transparent;\r\n");
      out.write("        content:\"\";\r\n");
      out.write("        position: relative;\r\n");
      out.write("        top:-10px;\r\n");
      out.write("        right:-5px;\r\n");
      out.write("    }\r\n");
      out.write("    .sort.asc:after {\r\n");
      out.write("        width: 0;\r\n");
      out.write("        height: 0;\r\n");
      out.write("        border-left: 5px solid transparent;\r\n");
      out.write("        border-right: 5px solid transparent;\r\n");
      out.write("        border-top: 5px solid #fff;\r\n");
      out.write("        content:\"\";\r\n");
      out.write("        position: relative;\r\n");
      out.write("        top:13px;\r\n");
      out.write("        right:-5px;\r\n");
      out.write("    }\r\n");
      out.write("    .sort.desc:after {\r\n");
      out.write("        width: 0;\r\n");
      out.write("        height: 0;\r\n");
      out.write("        border-left: 5px solid transparent;\r\n");
      out.write("        border-right: 5px solid transparent;\r\n");
      out.write("        border-bottom: 5px solid #fff;\r\n");
      out.write("        content:\"\";\r\n");
      out.write("        position: relative;\r\n");
      out.write("        top:-10px;\r\n");
      out.write("        right:-5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    /*#list {*/\r\n");
      out.write("        /*list-style: none;*/\r\n");
      out.write("        /*padding-left: 0;*/\r\n");
      out.write("    /*}*/\r\n");
      out.write("\r\n");
      out.write("    .list .sort-handle {\r\n");
      out.write("        display: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .list .ui-selected .sort-handle\r\n");
      out.write("    {\r\n");
      out.write("        display: inline;\r\n");
      out.write("        padding: 0 0.5em;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    li.ui-selected {\r\n");
      out.write("        background-color: #8888cc;\r\n");
      out.write("        color: white;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        background-image: none;\r\n");
      out.write("    }\r\n");
      out.write("    li.ui-selecting {\r\n");
      out.write("        background-color: #ccccff;\r\n");
      out.write("        color: white;\r\n");
      out.write("        background-image: none;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</style>");
    } catch( java.lang.Throwable t ) {
      if( t instanceof javax.servlet.jsp.SkipPageException )
          throw (javax.servlet.jsp.SkipPageException) t;
      if( t instanceof java.io.IOException )
          throw (java.io.IOException) t;
      if( t instanceof java.lang.IllegalStateException )
          throw (java.lang.IllegalStateException) t;
      if( t instanceof javax.servlet.jsp.JspException )
          throw (javax.servlet.jsp.JspException) t;
      throw new javax.servlet.jsp.JspException(t);
    } finally {
      jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,super.getJspContext());
      ((org.apache.jasper.runtime.JspContextWrapper) jspContext).syncEndTagFile();
      _jspDestroy();
    }
  }

  private boolean _jspx_meth_base_005fbuttonPermission_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:buttonPermission
    org.apache.jsp.tag.web.buttonPermission_tag _jspx_th_base_005fbuttonPermission_005f0 = (new org.apache.jsp.tag.web.buttonPermission_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fbuttonPermission_005f0);
    _jspx_th_base_005fbuttonPermission_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005fbuttonPermission_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    // /WEB-INF/tags/sortableClinicItem.tag(33,2) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f0.setKey("global.crud.save");
    // /WEB-INF/tags/sortableClinicItem.tag(33,2) name = classNames type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f0.setClassNames("uk-button uk-button-success");
    // /WEB-INF/tags/sortableClinicItem.tag(33,2) name = id type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f0.setId("userView-save");
    _jspx_th_base_005fbuttonPermission_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fbuttonPermission_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005foptiion_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:optiion
    org.apache.jsp.tag.web.optiion_tag _jspx_th_base_005foptiion_005f0 = (new org.apache.jsp.tag.web.optiion_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005foptiion_005f0);
    _jspx_th_base_005foptiion_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005foptiion_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    // /WEB-INF/tags/sortableClinicItem.tag(60,8) name = widthValue type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005foptiion_005f0.setWidthValue("40");
    // /WEB-INF/tags/sortableClinicItem.tag(60,8) name = absulotePath type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005foptiion_005f0.setAbsulotePath((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${operationAllUrl}", java.lang.String.class, (javax.servlet.jsp.PageContext)this.getJspContext(), null));
    // /WEB-INF/tags/sortableClinicItem.tag(60,8) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005foptiion_005f0.setName("orders_customized");
    // /WEB-INF/tags/sortableClinicItem.tag(60,8) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005foptiion_005f0.setKey("");
    // /WEB-INF/tags/sortableClinicItem.tag(60,8) name = noneSelectedText type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005foptiion_005f0.setNoneSelectedText("select...");
    // /WEB-INF/tags/sortableClinicItem.tag(60,8) name = clickEventMethod type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005foptiion_005f0.setClickEventMethod("clickCustomizeEvent");
    // /WEB-INF/tags/sortableClinicItem.tag(60,8) name = optgrouptoggleEventMethod type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005foptiion_005f0.setOptgrouptoggleEventMethod("optgrouptoggleCustomizeEvent");
    // /WEB-INF/tags/sortableClinicItem.tag(60,8) name = unCheckAllEventMethod type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005foptiion_005f0.setUnCheckAllEventMethod("unCheckAllCustomizeEvent");
    // /WEB-INF/tags/sortableClinicItem.tag(60,8) name = beforeCloseEventMethod type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005foptiion_005f0.setBeforeCloseEventMethod("beforeCloseCustomizeEvent");
    // /WEB-INF/tags/sortableClinicItem.tag(60,8) name = selectedList type = java.lang.Integer reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005foptiion_005f0.setSelectedList(new java.lang.Integer(0));
    _jspx_th_base_005foptiion_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_base_005foptiion_005f0, null));
    _jspx_th_base_005foptiion_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005foptiion_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005fdialogConfirm_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:dialogConfirm
    org.apache.jsp.tag.web.dialogConfirm_tag _jspx_th_base_005fdialogConfirm_005f0 = (new org.apache.jsp.tag.web.dialogConfirm_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fdialogConfirm_005f0);
    _jspx_th_base_005fdialogConfirm_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005fdialogConfirm_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    // /WEB-INF/tags/sortableClinicItem.tag(77,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fdialogConfirm_005f0.setName("dialogDeleteNameCategory");
    // /WEB-INF/tags/sortableClinicItem.tag(77,0) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fdialogConfirm_005f0.setKey("action.alert.areYouSure.delete");
    // /WEB-INF/tags/sortableClinicItem.tag(77,0) name = yesFunction type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fdialogConfirm_005f0.setYesFunction("yesDeleteNameCategory");
    _jspx_th_base_005fdialogConfirm_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fdialogConfirm_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005fdialogConfirm_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:dialogConfirm
    org.apache.jsp.tag.web.dialogConfirm_tag _jspx_th_base_005fdialogConfirm_005f1 = (new org.apache.jsp.tag.web.dialogConfirm_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fdialogConfirm_005f1);
    _jspx_th_base_005fdialogConfirm_005f1.setJspContext(_jspx_page_context);
    _jspx_th_base_005fdialogConfirm_005f1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    // /WEB-INF/tags/sortableClinicItem.tag(78,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fdialogConfirm_005f1.setName("dialogDeleteItem");
    // /WEB-INF/tags/sortableClinicItem.tag(78,0) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fdialogConfirm_005f1.setKey("action.alert.areYouSure.delete");
    // /WEB-INF/tags/sortableClinicItem.tag(78,0) name = yesFunction type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fdialogConfirm_005f1.setYesFunction("yesDeleteItem");
    _jspx_th_base_005fdialogConfirm_005f1.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fdialogConfirm_005f1);
    return false;
  }

  private boolean _jspx_meth_base_005fdialogAlert_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:dialogAlert
    org.apache.jsp.tag.web.dialogAlert_tag _jspx_th_base_005fdialogAlert_005f0 = (new org.apache.jsp.tag.web.dialogAlert_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fdialogAlert_005f0);
    _jspx_th_base_005fdialogAlert_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005fdialogAlert_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    // /WEB-INF/tags/sortableClinicItem.tag(79,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fdialogAlert_005f0.setName("dialogAlertDuplicatItem");
    // /WEB-INF/tags/sortableClinicItem.tag(79,0) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fdialogAlert_005f0.setKey("action.alert.duplicate.item");
    _jspx_th_base_005fdialogAlert_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fdialogAlert_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005ftestBox_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:testBox
    org.apache.jsp.tag.web.testBox_tag _jspx_th_base_005ftestBox_005f0 = (new org.apache.jsp.tag.web.testBox_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005ftestBox_005f0);
    _jspx_th_base_005ftestBox_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005ftestBox_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    // /WEB-INF/tags/sortableClinicItem.tag(83,8) name = styleClass type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005ftestBox_005f0.setStyleClass("small");
    // /WEB-INF/tags/sortableClinicItem.tag(83,8) name = styledivLabel type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005ftestBox_005f0.setStyledivLabel("width:10%;height:100%");
    // /WEB-INF/tags/sortableClinicItem.tag(83,8) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005ftestBox_005f0.setName("nameCategory");
    // /WEB-INF/tags/sortableClinicItem.tag(83,8) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005ftestBox_005f0.setKey("clinic.patient.firstName");
    _jspx_th_base_005ftestBox_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005ftestBox_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005ffooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:footer
    org.apache.jsp.tag.web.footer_tag _jspx_th_base_005ffooter_005f0 = (new org.apache.jsp.tag.web.footer_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005ffooter_005f0);
    _jspx_th_base_005ffooter_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005ffooter_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    _jspx_th_base_005ffooter_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005ffooter_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    // /WEB-INF/tags/sortableClinicItem.tag(158,256) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/resources/images/delete/Actions-button-cancel-icon8.png");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      throw new javax.servlet.jsp.SkipPageException();
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    // /WEB-INF/tags/sortableClinicItem.tag(164,386) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/resources/images/delete/Actions-button-cancel-icon8.png");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      throw new javax.servlet.jsp.SkipPageException();
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) this ));    // /WEB-INF/tags/sortableClinicItem.tag(541,25) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      throw new javax.servlet.jsp.SkipPageException();
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("        ");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
