/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2020-02-01 11:49:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.clinic.patient.ConfigurablePatientRecord.fileBaseItems;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import org.springframework.web.util.UrlPathHelper;
import java.util.List;
import com.artonis.clinic.core.model.MedicalTest;
import com.artonis.clinic.core.model.MedicalTestVisitQueue;
import java.util.ResourceBundle;
import java.util.ArrayList;
import org.apache.commons.lang3.StringEscapeUtils;
import com.artonis.clinic.customize.view.UserLabTestItemView;
import com.mongodb.DBObject;
import com.artonis.core.base.core.Date;

public final class CurrentLabTestAndResult_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.2.2.RELEASE.jar", Long.valueOf(1580195756303L));
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1580195752738L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/matab/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323245778000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/matab/WEB-INF/lib/spring-webmvc-4.2.2.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1444873464000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.artonis.clinic.customize.view.UserLabTestItemView");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.ResourceBundle");
    _jspx_imports_classes.add("com.mongodb.DBObject");
    _jspx_imports_classes.add("com.artonis.clinic.core.model.MedicalTestVisitQueue");
    _jspx_imports_classes.add("com.artonis.core.base.core.Date");
    _jspx_imports_classes.add("com.artonis.clinic.core.model.MedicalTest");
    _jspx_imports_classes.add("org.springframework.web.util.UrlPathHelper");
    _jspx_imports_classes.add("org.apache.commons.lang3.StringEscapeUtils");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

    ResourceBundle resource = ResourceBundle.getBundle("application_fa");
    String areUShureDeleteRow = resource.getString("clinic.patientfile.confirm.delete.row");
    String areUShureAddLabTest = resource.getString("clinic.patientfile.confirm.add.new.labtest");
    List<String> idClassRemoveList = new ArrayList<String>();
    String visitQueueId = (String) request.getAttribute("visitQueueId");
    Date curDate = new Date(System.currentTimeMillis());
    String curStringDate = curDate.toString();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<div>\r\n");
      out.write("    <div>\r\n");
      out.write("        <div class=\"uk-width-1-1\" id=\"drug-kanban-static\" style=\" height:100%\">\r\n");
      out.write("            <label dir=\"ltr\">All LabTest</label>\r\n");
      out.write("            <input type=\"hidden\" id=\"p-labtestMultiSelect-current\" style=\"direction:ltr; width: 100%; height:100% \"/>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            <button name=\"Add\" id=\"add\" onclick=\"addClick()\" title=\"Add\">Add current LabTest</button>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"tableDiv\">\r\n");
      out.write("            <table id=\"table\" height=\"100%\" width=\"60%\" style=\"text-align: center;background-color: #ffffff;\" border=\"2\" dir=\"ltr\">\r\n");
      out.write("                <tr>\r\n");
      out.write("                    <th id=\"labTest\" style=\"width: 40%\">\r\n");
      out.write("                        lab test\r\n");
      out.write("                    </th>\r\n");
      out.write("                    <th id=\"values\" style=\"width: 20%\">\r\n");
      out.write("                        value\r\n");
      out.write("                    </th>\r\n");
      out.write("                    <th id=\"dates\" style=\"width: 20%\">\r\n");
      out.write("                        date\r\n");
      out.write("                    </th>\r\n");
      out.write("                    <th id=\"delete\">\r\n");
      out.write("                        delete\r\n");
      out.write("                    </th>\r\n");
      out.write("                    <th id=\"highlightCurrentLabTest\">\r\n");
      out.write("                        Highlight\r\n");
      out.write("                    </th>\r\n");
      out.write("                </tr>\r\n");
      out.write("            </table>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div style=\"margin-top: 5px;\">\r\n");
      out.write("\t\t\t<!-- <button id=\"saveLabTestItemBtn\" onclick=\"saveLabTestItem()\" class=\"uk-button uk-button-success\" disabled >Save Lab Test</button> -->\r\n");
      out.write("\t\t\t<!-- <button id=\"addToLabTestReportBtn\" onclick=\"addToLabTestReport()\" class=\"uk-button uk-button-success\" disabled >Add To Lab Test Report</button> -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <div>\r\n");
      out.write("            ");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <br>\r\n");
      out.write("\r\n");
      out.write("    <div id=\"dialog-f\" title='select lab test' style=\"display:none;direction: ltr;height: 100% !important;\">\r\n");
      out.write("        <form class=\"toPopup\" style=\"direction: ltr\">\r\n");
      out.write("            <input type=\"text\" id=\"date-current-labtest\" value=\"");
      out.print(curStringDate);
      out.write("\" class=\"uk-width-1-1 currentLabtestDatePicker\" style=\"width: 100px; text-align: center;\"/>\r\n");
      out.write("            ");

                int rowPerColumn = 10;
                int column = 5;
                List<UserLabTestItemView> userLabTestList = (List<UserLabTestItemView>) request.getAttribute("userLabTestList");
                int index = 0;
                Long currentCoding = 0L;
                Long subCurrentCoding = 0L;
                Long previousCoding = 0L;
                if (userLabTestList == null || userLabTestList.size() == 0) {
            
      out.write("\r\n");
      out.write("            <table id=\"dialog-current-labtest-table\">");

                }
                for (UserLabTestItemView userLabTestItemView : userLabTestList) {
                    currentCoding=userLabTestItemView.getUser_labtest_id();
                    if (index == 0) {
                         if(currentCoding!=null){
                              previousCoding=currentCoding;
                         }
            
      out.write("\r\n");
      out.write("                <table id=\"dialog-current-labtest-table\">\r\n");
      out.write("                    <tr id=\"current-labtest-coding-");
      out.print(currentCoding);
      out.write("\" >\r\n");
      out.write("\t\t\t            <tr style=\"background-color: #9cf;\">\r\n");
      out.write("\t\t\t           \t\t<td>\r\n");
      out.write("\t\t\t                   <label for=\"");
      out.print(userLabTestItemView.getName());
      out.write("-group-customize\"><span style=\"font-weight:bold\">");
      out.print(userLabTestItemView.getName());
      out.write("</span>\r\n");
      out.write("\t\t\t                   </label>\r\n");
      out.write("\t\t\t               </td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("                        <td style=\"width: 15%\" align=\"right\">\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"checkbox\" name=\"");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\" style=\" opacity: 0; \"\r\n");
      out.write("                                   id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-checkbox\"/>\r\n");
      out.write("                            <label for=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-checkbox\">");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td style=\"width: 5%\">\r\n");
      out.write("                            <textarea rows=\"1\" id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-value\" onkeyup=\"textArea_popup_onchange(this)\"\r\n");
      out.write("                                      style=\"resize: none;width: 100%;\"></textarea>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        ");

                        } else if ((previousCoding == null && currentCoding != null) ||
                                (previousCoding != null && currentCoding == null) ||
                                ((previousCoding != null && currentCoding != null) && !previousCoding.equals(currentCoding))) {
                            previousCoding = currentCoding;
                            subCurrentCoding=0L;
                            int def = 0;
                            if (index % column != 0) {
                                def = column - (index % column);
                                index += column - (index % column);
                                if (def > 0) {
                                    for (int j = 0; j < def; j++) {
      out.write("\r\n");
      out.write("                        <td>&nbsp;</td><td>&nbsp;</td>\r\n");
      out.write("                        ");

                                    }
                                }

                            }
                        
      out.write("\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    <tr id=\"current-labtest-coding-");
      out.print(currentCoding);
      out.write("\" >\r\n");
      out.write("\t\t\t            <tr style=\"background-color: #9cf;\">\r\n");
      out.write("\t\t\t               <td>\r\n");
      out.write("\t\t\t                   <label for=\"");
      out.print(userLabTestItemView.getName());
      out.write("-group-customize\"><span style=\"font-weight:bold\">");
      out.print(userLabTestItemView.getName());
      out.write("</span>\r\n");
      out.write("\t\t\t                   </label>\r\n");
      out.write("\t\t\t               </td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t               <td></td>\r\n");
      out.write("\t\t\t            </tr>\r\n");
      out.write("                        <td style=\"width: 15%\" align=\"right\">\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"checkbox\" name=\"");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\" style=\" opacity: 0; \"\r\n");
      out.write("                                   id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-checkbox\"/>\r\n");
      out.write("                            ");
      out.write("\r\n");
      out.write("                            <label for=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-checkbox\">");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td style=\"width: 5%\">\r\n");
      out.write("                            <textarea rows=\"1\" id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-value\" onkeyup=\"textArea_popup_onchange(this)\"\r\n");
      out.write("                                      style=\"resize: none;width: 100%;\"></textarea>\r\n");
      out.write("                        </td>\r\n");
      out.write("                            ");

                    } else if (index % column == 0) {
                          String trId="";
                         if(subCurrentCoding==0){
                            subCurrentCoding++;
                            trId=String.valueOf(currentCoding)+"_"+String.valueOf(subCurrentCoding);
                            idClassRemoveList.add(String.valueOf(currentCoding));
                         }else {
                            subCurrentCoding++;
                            trId=String.valueOf(currentCoding)+"_"+String.valueOf(subCurrentCoding);
                            idClassRemoveList.add(String.valueOf(currentCoding)+"_"+String.valueOf(subCurrentCoding-1));
                         }
                    
      out.write("\r\n");
      out.write("                    <tr id=\"current-labtest-coding-");
      out.print(trId);
      out.write("\" >\r\n");
      out.write("                        <td style=\"width: 15%\" align=\"right\">\r\n");
      out.write("                            <input type=\"checkbox\" name=\"");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\" style=\" opacity: 0; \"\r\n");
      out.write("                                   id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-checkbox\"/>\r\n");
      out.write("                            <label for=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-checkbox\">");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td style=\"width: 5%\">\r\n");
      out.write("                            <textarea rows=\"1\" id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-value\"  onkeyup='textArea_popup_onchange(this)'\r\n");
      out.write("                                      style=\"resize: none;width: 100%;\"></textarea>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        ");

                        } else if (index % column != 0 && index % column != column - 1) {
                        
      out.write("\r\n");
      out.write("                        <td style=\"width: 15%\" align=\"right\">\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"checkbox\" name=\"");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\" style=\" opacity: 0; \"\r\n");
      out.write("                                   id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-checkbox\"/>\r\n");
      out.write("                            <label for=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-checkbox\">");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td style=\"width: 5%\">\r\n");
      out.write("                            <textarea rows=\"1\" id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-value\" onkeyup='textArea_popup_onchange(this)'\r\n");
      out.write("                                      style=\"resize: none;width: 100%;\"></textarea>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        ");

                        } else if (index % column == column - 1) {
                        
      out.write("\r\n");
      out.write("                        <td style=\"width: 15%\" align=\"right\">\r\n");
      out.write("\r\n");
      out.write("                            <input type=\"checkbox\" name=\"");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\"  style=\" opacity: 0; \"\r\n");
      out.write("                                   id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-checkbox\"/>\r\n");
      out.write("                            <label for=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-checkbox\">");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\r\n");
      out.write("                            </label>\r\n");
      out.write("                        </td>\r\n");
      out.write("                        <td style=\"width: 5%\">\r\n");
      out.write("                            <textarea rows=\"1\" id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-current-labtest-value\" onkeyup='textArea_popup_onchange(this)'\r\n");
      out.write("                                      style=\"resize: none;width: 100%;\"></textarea>\r\n");
      out.write("                        </td>\r\n");
      out.write("                    </tr>\r\n");
      out.write("                    ");

                            }
                            index++;
                        }
                        if(subCurrentCoding==0){
                            idClassRemoveList.add(String.valueOf(currentCoding));
                        }else {
                            idClassRemoveList.add(String.valueOf(currentCoding)+"_"+String.valueOf(subCurrentCoding));
                        }
                    
      out.write("\r\n");
      out.write("                </table>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"dialog-confirm-delete-current-labtest\" style=\"display:none;direction: rtl;height: 100% !important;\">\r\n");
      out.write("    <p>");
      out.print(areUShureDeleteRow);
      out.write("\r\n");
      out.write("    </p>\r\n");
      out.write("</div>\r\n");
      out.write("<div id=\"dialog-confirm-save-current-labtest\" style=\"display:none;direction: rtl;height: 100% !important;\">\r\n");
      out.write("    <p>");
      out.print(areUShureAddLabTest);
      out.write("\r\n");
      out.write("    </p>\r\n");
      out.write("</div>\r\n");
      out.write("<script>\r\n");
      out.write("\r\n");
      out.write("    function activeCurrentLabtestDatePicker() {\r\n");
      out.write("        $(\".currentLabtestDatePicker:not(.pdp-el)\").persianDatepicker({\r\n");
      out.write("            onShow: function () {\r\n");
      out.write("                setTimeout(function () {\r\n");
      out.write("                    $('.pdp-default').css('z-index', 99999999999999);\r\n");
      out.write("                }, 0);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("function textArea_popup_onchange(e){\r\n");
      out.write("    var id=e.id.split('-current-labtest-value')[0];\r\n");
      out.write("    var checkBox=$(\"#\"+id+\"-current-labtest-checkbox\");\r\n");
      out.write("    if(e.value.length>0){\r\n");
      out.write("        checkBox.attr('checked', true);\r\n");
      out.write("        checkBox.prop('checked', true);\r\n");
      out.write("    }else{\r\n");
      out.write("        checkBox.attr('checked', false);\r\n");
      out.write("        checkBox.prop('checked', false);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function textArea_onKeyUp(e){\r\n");
      out.write("    $(\"#\"+e.id+'-current-labtest-value').val(e.value);\r\n");
      out.write("    enableSaveLabTestItemBtnAndAddToLabTestReportBtn();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function selectAllCurrentLabTestCheckBox(e) {\r\n");
      out.write("\r\n");
      out.write("    var checkBoxElementArray = $(\"#dialog-f\").find(\":checkbox\");\r\n");
      out.write("    for (var i = 1; i < checkBoxElementArray.length; i++) {\r\n");
      out.write("//        checkBoxElementArray[i].checked = e.checked;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
 for (int i=0; i<idClassRemoveList.size(); i++) { 
      out.write("\r\n");
      out.write("    $(\"#current-labtest-coding-\" + \"");
      out.print( idClassRemoveList.get(i) );
      out.write("\").removeClass();\r\n");
 } 
      out.write("\r\n");
      out.write("function saveCurrentLabTest(newItemArray) {\r\n");
      out.write("    var data = {};\r\n");
      out.write("    data.newLabTestCurrentOrder = newItemArray;\r\n");
      out.write("    if (newItemArray.length > 0) {\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            url:'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("' + '/clinic/patient/visitMobileBase/saveMedicalTest/',\r\n");
      out.write("            contentType:\"application/json; charset=utf-8\",\r\n");
      out.write("            data:JSON.stringify(data),\r\n");
      out.write("            dataType:'json',\r\n");
      out.write("            type:'POST',\r\n");
      out.write("            success:function (data, success, xhr) {\r\n");
      out.write("                if (data.saveMedicalTest != undefined) {\r\n");
      out.write("                    var split = data.saveMedicalTest.split(';;;;');\r\n");
      out.write("                    if (split.length > 1) {\r\n");
      out.write("                        for (var i = 0; i < split.length - 1; i = i + 2) {\r\n");
      out.write("                            rowNumber++;\r\n");
      out.write("                            $('#table').append('<tr id=\"' + split[i] +'-'+rowNumber +'-row' + '\"></td>' +\r\n");
      out.write("                            '<td contente=\"true\">' + split[i + 1] + '</td>' +\r\n");
      out.write("                            '<td contente=\"true\"> <textarea onkeyup=\"textArea_onKeyUp(this)\" id=\"' + split[i] +'-'+rowNumber+ '\" style=\" width: 100%;resize:none; \"/></td>' +\r\n");
      out.write("                            '<td contente=\"true\"><input type=\"text\" id=\"'+split[i]+'-'+rowNumber+'-labtest-current-date\" value=\"");
      out.print(curStringDate);
      out.write("\" class=\"uk-width-1-1 currentLabtestDatePicker\" style=\"width: 100px; text-align: center;\"/></td>' +\r\n");
      out.write("                            '<td><input type=\"button\" value=\"delete\" class=\"uk-button-mini uk-button-danger\" onclick=\"deleteClick(this)\" /></td>' +\r\n");
      out.write("                            '<td><input type=\"checkbox\" id=\"'+split[i]+'-'+rowNumber+'-currentLabtest-checkbox-highlight'+'\"</td></tr>' + '');\r\n");
      out.write("\r\n");
      out.write("                        }\r\n");
      out.write("                        initCurrentLabtestSelect2(split[1], split[0]);\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            },\r\n");
      out.write("            error:function (e) {\r\n");
      out.write("//                alert('Error121212: ' + e.responseText);\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("var selectCurrentLabTestArrayElement=[];\r\n");
      out.write("var initCurrentLabState=true;\r\n");
      out.write("    var rowNumber=0;\r\n");

//if(!(request.getAttribute("labTestCurrent") instanceof String)){
//List<MedicalTestVisitQueue> list = (List)request.getAttribute("labTestCurrent");
//if(list!=null){
//for(int i=0; i <list.size(); i++) {
//MedicalTestVisitQueue medicalTestVisitQueue=list.get(i);
//long medicalTestId=medicalTestVisitQueue.getMedicalTest_id();
//String medicaltestname=medicalTestVisitQueue.getMedicalTestName();
//String value=medicalTestVisitQueue.getValue();

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

 Boolean labTestIsHighlight=false;
 String labTestDate="";
 String labTestName="";
 String labTestId="";
 String labTestValue="";
 if(!(request.getAttribute("labTestResultWithValueList") instanceof String) && request.getAttribute("labTestResultWithValueList")!=null){
    List<DBObject> labTestResultWithValueList = (List)request.getAttribute("labTestResultWithValueList");
    for (DBObject dbObject : labTestResultWithValueList) {

           if(dbObject.get("labTestIsHighlight")!=null){
                labTestIsHighlight=(Boolean) dbObject.get("labTestIsHighlight");
           }
           if(dbObject.get("labTestDate")!=null){
                 labTestDate= dbObject.get("labTestDate").toString();
           }
           if(dbObject.get("labTestName")!=null){
                 labTestName= dbObject.get("labTestName").toString();
           }
           if(dbObject.get("labTestId")!=null){
                 labTestId= dbObject.get("labTestId").toString();
           }
           if(dbObject.get("labTestVal")!=null){
                 labTestValue= dbObject.get("labTestVal").toString();
           }
           
      out.write("\r\n");
      out.write("            rowNumber++;\r\n");
      out.write("            var medicaltestId = '");
      out.print(labTestId);
      out.write("';\r\n");
      out.write("            var medicaltestname = '");
      out.print(labTestName);
      out.write("';\r\n");
      out.write("            var labTestIsHighlight = '");
      out.print(labTestIsHighlight);
      out.write("';\r\n");
      out.write("            var labTestDate = '");
      out.print(labTestDate);
      out.write("';\r\n");
      out.write("            selectCurrentLabTestArrayElement[selectCurrentLabTestArrayElement.length]=medicaltestId;\r\n");
      out.write("            var value = '");
      out.print(StringEscapeUtils.escapeEcmaScript(labTestValue));
      out.write("';\r\n");
      out.write("            $('#table').append('<tr id=\"' + medicaltestId +'-'+rowNumber +'-row' + '\"></td>' +\r\n");
      out.write("            '<td contente=\"true\">' + medicaltestname + '</td>' +\r\n");
      out.write("            '<td contente=\"true\"> <textarea onkeyup=\"textArea_onKeyUp(this)\" id=\"' + medicaltestId +'-'+rowNumber+ '\" style=\" width: 100%;resize: none; \">");
      out.print(StringEscapeUtils.escapeEcmaScript(labTestValue));
      out.write("</textarea></td><td contente=\"true\"><input type=\"text\" id=\"'+medicaltestId+'-'+rowNumber+'-labtest-current-date\" value=\"'+labTestDate+'\" class=\"uk-width-1-1 currentLabtestDatePicker\" style=\"width: 100px; text-align: center;\"/></td><td><input type=\"button\" value=\"delete\" class=\"uk-button-mini uk-button-danger\" onclick=\"deleteClick(this)\" /></td><td><input type=\"checkbox\" id=\"'+medicaltestId+'-'+rowNumber+'-currentLabtest-checkbox-highlight'+'\"</td></tr>' + '');\r\n");
      out.write("            if(labTestIsHighlight=='true'){\r\n");
      out.write("                $('#'+medicaltestId+'-'+rowNumber+'-currentLabtest-checkbox-highlight').prop('checked',true)\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("    ");


        }
     }


    //           }
    //  }
    //  }
    
      out.write("\r\n");
      out.write("var cancelButtonCurrentLabTestOrderClick = false;\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\"#dialog-f\").dialog({\r\n");
      out.write("\t    autoOpen:false,\r\n");
      out.write("\t    show:{\r\n");
      out.write("\t        effect:\"slide\",\r\n");
      out.write("\t        duration:300\r\n");
      out.write("\t    },\r\n");
      out.write("\t    hide:{\r\n");
      out.write("\t        effect:\"slide\",\r\n");
      out.write("\t        duration:300\r\n");
      out.write("\t    },\r\n");
      out.write("\t    height:800,\r\n");
      out.write("\t    width:900,\r\n");
      out.write("\t    modal:true,\r\n");
      out.write("\t    buttons:{\r\n");
      out.write("\t        \"ok\":function () {\r\n");
      out.write("\t            popupCurrentLabTestOkButton();\r\n");
      out.write("\t            $(this).dialog(\"close\");\r\n");
      out.write("\t            enableSaveLabTestItemBtnAndAddToLabTestReportBtn();\r\n");
      out.write("\t        },\r\n");
      out.write("\t        \"cancel\":function () {\r\n");
      out.write("\t            cancelButtonCurrentLabTestOrderClick = true;\r\n");
      out.write("\t            $(this).dialog(\"close\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t    },\r\n");
      out.write("\t    close:function (event, ui) {\r\n");
      out.write("\t        if (event.which != undefined || cancelButtonCurrentLabTestOrderClick == true) {\r\n");
      out.write("\t            cancelEventCurrentLabTest();\r\n");
      out.write("\t            cancelButtonCurrentLabTestOrderClick = false;\r\n");
      out.write("\t        }\r\n");
      out.write("\t        $(this).dialog(\"close\");\r\n");
      out.write("\t    },\r\n");
      out.write("\t    open:function (event, ui) {\r\n");
      out.write("//\t        arrayCheckedBoxBeforeOpenedCurrentLabTest = $(\"#dialog-f\").find(\":checkbox:checked\");\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("\t//\r\n");
      out.write("\tinitCurrentLabtestSelect2();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#dialog-f textarea').keypress(function(e){\r\n");
      out.write("\tif (e.keyCode == 13) {\r\n");
      out.write("\r\n");
      out.write("\t\tvar index = $('#dialog-f textarea').index(this) + 1;\r\n");
      out.write("\t\t$('#dialog-f textarea, #dialog-f+div button').eq(index).focus();\r\n");
      out.write("\r\n");
      out.write("\t\te.preventDefault();\r\n");
      out.write("\t}\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#dialog-f textarea').focus(function(e){\r\n");
      out.write("\t$('#dialog-f label').removeClass('hasFocus');\r\n");
      out.write("\tvar id = $(this).attr('id');\r\n");
      out.write("\tid = id.replace('value', 'checkbox');\r\n");
      out.write("\t$('#dialog-f label[for=\"' + id + '\"]').addClass('hasFocus');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$('#dialog-f textarea').blur(function(e){\r\n");
      out.write("\tvar id = $(this).attr('id');\r\n");
      out.write("\tid = id.replace('value', 'checkbox');\r\n");
      out.write("\t$('#dialog-f label[for=\"' + id + '\"]').removeClass('hasFocus');\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$(\"#dialog-confirm-delete-current-labtest\").dialog({\r\n");
      out.write("\t    autoOpen:false,\r\n");
      out.write("\t    show:{\r\n");
      out.write("\t        effect:\"slide\",\r\n");
      out.write("\t        duration:300\r\n");
      out.write("\t    },\r\n");
      out.write("\t    hide:{\r\n");
      out.write("\t        effect:\"slide\",\r\n");
      out.write("\t        duration:300\r\n");
      out.write("\t    },\r\n");
      out.write("\t    height:800,\r\n");
      out.write("\t    width:800,\r\n");
      out.write("\t    modal:true,\r\n");
      out.write("\t    buttons:{\r\n");
      out.write("\t        \"Yes\":function () {\r\n");
      out.write("\t            if ($(this).data('contents') != undefined) {\r\n");
      out.write("\t                deleteCurrentLabTestRow($(this).data('contents'));\r\n");
      out.write("\t            } else if ($(this).data('e') != undefined) {\r\n");
      out.write("\t                var id = $(this).data('e').choice.id;\r\n");
      out.write("\t                var idStr=\"\";\r\n");
      out.write("\t                for(var j=0;j<id.length;j++){\r\n");
      out.write("\t                    idStr+=id[j];\r\n");
      out.write("\t                }\r\n");
      out.write("\t                if(idStr.length>0){\r\n");
      out.write("\t                    id=idStr;\r\n");
      out.write("\t                }\r\n");
      out.write("\t                $('#' +id + '-row').remove();\r\n");
      out.write("\t                if ($('#' + id + '-operation-current-checkbox-rowOperation').length > 0) {\r\n");
      out.write("\t                    $('#' + id + '-operation-current-checkbox-rowOperation').remove();\r\n");
      out.write("\t                    var arrayCheckBox = $(\"#dialog-current-operation\").find(\":checkbox:checked\");\r\n");
      out.write("\t                    for (var i = 0; i < arrayCheckBox.length; i++) {\r\n");
      out.write("\t                        if (arrayCheckBox[i].id == id + \"-operation-current-checkbox\") {\r\n");
      out.write("\t                            $(\"#\" + id + '-operation-current-checkbox').attr('checked', false);\r\n");
      out.write("\t                            $(\"#\" + id + '-operation-current-checkbox').prop('checked', false);\r\n");
      out.write("\t                        }\r\n");
      out.write("\t                    }\r\n");
      out.write("\t                }\r\n");
      out.write("\t            }\r\n");
      out.write("\t            $(this).dialog(\"close\");\r\n");
      out.write("\t            enableSaveLabTestItemBtnAndAddToLabTestReportBtn();\r\n");
      out.write("\t        },\r\n");
      out.write("\t        \"No\":function () {\r\n");
      out.write("\t            if ($(this).data('e') != undefined) {\r\n");
      out.write("\t                selectCurrentLabtestOption($(this).data('e').choice.id);\r\n");
      out.write("\t            }\r\n");
      out.write("\t            $(this).dialog(\"close\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("    activeCurrentLabtestDatePicker();\r\n");
      out.write("\t$(\"#dialog-confirm-save-current-labtest\").dialog({\r\n");
      out.write("\t    autoOpen:false,\r\n");
      out.write("\t    show:{\r\n");
      out.write("\t        effect:\"slide\",\r\n");
      out.write("\t        duration:300\r\n");
      out.write("\t    },\r\n");
      out.write("\t    hide:{\r\n");
      out.write("\t        effect:\"slide\",\r\n");
      out.write("\t        duration:300\r\n");
      out.write("\t    },\r\n");
      out.write("\t    height:800,\r\n");
      out.write("\t    width:800,\r\n");
      out.write("\t    modal:true,\r\n");
      out.write("\t    buttons:{\r\n");
      out.write("\t        \"ok\":function () {\r\n");
      out.write("\t            var newItemArray = $(this).data('newItemArray');\r\n");
      out.write("\t            var itemArray = [];\r\n");
      out.write("\t            itemArray[0] = newItemArray[0];\r\n");
      out.write("\t            saveCurrentLabTest(itemArray);\r\n");
      out.write("\t            $(this).dialog(\"close\");\r\n");
      out.write("\t        },\r\n");
      out.write("\t        \"cancel\":function () {\r\n");
      out.write("\t            var newItemArray = $(this).data('newItemArray');\r\n");
      out.write("\t            deleteCurrentLabTestOption(newItemArray[1]);\r\n");
      out.write("\t            $(this).dialog(\"close\");\r\n");
      out.write("\t        }\r\n");
      out.write("\t    }\r\n");
      out.write("\t});\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function deleteCurrentLabTestRow(contents) {\r\n");
      out.write("    $('#' + contents[1].lastChild.id + '-row').remove();\r\n");
      out.write("    var arrayCheckedLabTest = $(\"#dialog-f\").find(\":checkbox:checked\");\r\n");
      out.write("    for (var i = 0; i < arrayCheckedLabTest.length; i++) {\r\n");
      out.write("        if (arrayCheckedLabTest[i].id == contents[1].lastChild.id + '-current-labtest-checkbox') {\r\n");
      out.write("//            arrayCheckedLabTest[i].checked = false;\r\n");
      out.write("            $(\"#\"+contents[1].lastChild.id+\"-current-labtest-value\").val(\"\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    var id = contents[1].lastChild.id;\r\n");
      out.write("    deleteCurrentLabTestOption(id);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("function deleteCurrentLabTestOption(id) {\r\n");
      out.write("    var labTestIdSelect2Array = $(\"#p-labtestMultiSelect-current\").select2('val');\r\n");
      out.write("    var newLabTestIdSelect2Array = [];\r\n");
      out.write("    var index = 0;\r\n");
      out.write("    for (var j = 0; j < labTestIdSelect2Array.length; j++) {\r\n");
      out.write("        if (id != labTestIdSelect2Array[j]) {\r\n");
      out.write("            newLabTestIdSelect2Array[index] = labTestIdSelect2Array[j];\r\n");
      out.write("            index++;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    $(\"#p-labtestMultiSelect-current\").select2('val', newLabTestIdSelect2Array);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("jQuery('body')\r\n");
      out.write("        .bind(\r\n");
      out.write("        'click',\r\n");
      out.write("        function (e) {\r\n");
      out.write("            if (\r\n");
      out.write("                    jQuery('#dialog-f').dialog('isOpen')\r\n");
      out.write("                            && !jQuery(e.target).is('.ui-dialog, a')\r\n");
      out.write("                            && !jQuery(e.target).closest('.ui-dialog').length\r\n");
      out.write("                            && event.target.nodeName != \"BUTTON\"\r\n");
      out.write("                            && !((jQuery(e.target).parent().parent().parent()[0].className=='pdp-default')\r\n");
      out.write("                            || (jQuery(e.target).parent().parent()[0].className=='pdp-default')\r\n");
      out.write("                            || (jQuery(e.target).parent()[0].className=='pdp-default'))\r\n");
      out.write("                    ) {\r\n");
      out.write("                jQuery('#dialog-f').dialog('close');\r\n");
      out.write("                popupCurrentLabTestOkButton();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write(");\r\n");
      out.write("\r\n");
      out.write("//var arrayCheckedBoxBeforeOpenedCurrentLabTest;\r\n");
      out.write("function cancelEventCurrentLabTest() {\r\n");
      out.write("    arrayCheckedBoxAfterCancel = $(\"#dialog-f\").find(\":checkbox:checked\");\r\n");
      out.write("    for (var i = 0; i < arrayCheckedBoxAfterCancel.length; i++) {\r\n");
      out.write("        $(\"#\" + arrayCheckedBoxAfterCancel[i].id).attr('checked', false);\r\n");
      out.write("        $(\"#\" + arrayCheckedBoxAfterCancel[i].id).prop('checked', false);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("//    for (var j = 0; j < arrayCheckedBoxBeforeOpenedCurrentLabTest.length; j++) {\r\n");
      out.write("//        $(\"#\" + arrayCheckedBoxBeforeOpenedCurrentLabTest[j].id).attr('checked', true);\r\n");
      out.write("//        $(\"#\" + arrayCheckedBoxBeforeOpenedCurrentLabTest[j].id).prop('checked', true);\r\n");
      out.write("//    }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function popupCurrentLabTestOkButton() {\r\n");
      out.write("    var currentLabTestWithValueArray = $('#table').parent().find('textarea');\r\n");
      out.write("    var arrayCheckedLabTest = $(\"#dialog-f\").find(\":checkbox:checked\");\r\n");
      out.write("    var selectedLabTestIds = $(\"#p-labtestMultiSelect-current\").select2('val');\r\n");
      out.write("    for (var i = 0; i < arrayCheckedLabTest.length; i++) {\r\n");
      out.write("//        var found = false;\r\n");
      out.write("//        for (var j = 0; j < currentLabTestWithValueArray.length; j++) {\r\n");
      out.write("//            if (arrayCheckedLabTest[i].id == currentLabTestWithValueArray[j].id + '-current-labtest-checkbox') {\r\n");
      out.write("//                found = true;\r\n");
      out.write("//                var textBoxValue = $(\"#\" + currentLabTestWithValueArray[j].id + \"-current-labtest-value\").val();\r\n");
      out.write("//                $('#'+currentLabTestWithValueArray[j].id).val(textBoxValue);\r\n");
      out.write("//                break;\r\n");
      out.write("//            }\r\n");
      out.write("//        }\r\n");
      out.write("        rowNumber++;\r\n");
      out.write("        if ( arrayCheckedLabTest[i].id != 'all-select-c-labtest-checkbox') {\r\n");
      out.write("            var id = arrayCheckedLabTest[i].id.split('-current-labtest-checkbox')[0];\r\n");
      out.write("            var textBoxValue = $(\"#\" + id + \"-current-labtest-value\").val();\r\n");
      out.write("            if(textBoxValue.trim().length>0){\r\n");
      out.write("                $('#table').append('<tr id=\"' + arrayCheckedLabTest[i].id.split('-current-labtest-checkbox')[0] +'-'+rowNumber +'-row' + '\"></td>' +\r\n");
      out.write("                '<td contente=\"true\">' + arrayCheckedLabTest[i].name + '</td><td contente=\"true\"> <textarea onkeyup=\"textArea_onKeyUp(this)\" style=\"width:100%;resize: none;\" id=\"' + arrayCheckedLabTest[i].id.split('-current-labtest-checkbox')[0] +'-'+rowNumber+ '\" style=\" width: 100%; \">'+textBoxValue+'</textarea></td>' +\r\n");
      out.write("                '<td contente=\"true\"><input type=\"text\" id=\"'+arrayCheckedLabTest[i].id.split('-current-labtest-checkbox')[0]+'-'+rowNumber+'-labtest-current-date\" value=\"");
      out.print(curStringDate);
      out.write("\" class=\"uk-width-1-1 currentLabtestDatePicker\" style=\"width: 100px; text-align: center;\"/></td>' +\r\n");
      out.write("                '<td><input type=\"button\" value=\"delete\" class=\"uk-button-mini uk-button-danger\" onclick=\"deleteClick(this)\" /></td>' +\r\n");
      out.write("                '<td><input type=\"checkbox\" id=\"'+arrayCheckedLabTest[i].id.split('-current-labtest-checkbox')[0]+'-'+rowNumber+'-currentLabtest-checkbox-highlight'+'\"</td></tr>' + '');\r\n");
      out.write("                $('#'+arrayCheckedLabTest[i].id.split('-current-labtest-checkbox')[0]+'-'+rowNumber+'-labtest-current-date').val($('#date-current-labtest').val());\r\n");
      out.write("                activeCurrentLabtestDatePicker();\r\n");
      out.write("            }\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    $('.pdp-default').hide();\r\n");
      out.write("\r\n");
      out.write("//    for (var w = 0; w < currentLabTestWithValueArray.length; w++) {\r\n");
      out.write("//        var f = false;\r\n");
      out.write("//        for (x = 0; x < arrayCheckedLabTest.length; x++) {\r\n");
      out.write("//            if (currentLabTestWithValueArray[w].id + '-current-labtest-checkbox' == arrayCheckedLabTest[x].id) {\r\n");
      out.write("//                f = true;\r\n");
      out.write("//                break;\r\n");
      out.write("//            }\r\n");
      out.write("//        }\r\n");
      out.write("//        if (f == false) {\r\n");
      out.write("//            for (var l = 0; l < selectedLabTestIds.length; l++) {\r\n");
      out.write("//                if (currentLabTestWithValueArray[w].id == selectedLabTestIds[l]) {\r\n");
      out.write("//                    f = true;\r\n");
      out.write("//                    break;\r\n");
      out.write("//                }\r\n");
      out.write("//            }\r\n");
      out.write("//            if (f == false) {\r\n");
      out.write("//                $('#' + currentLabTestWithValueArray[w].id + '-row').remove();\r\n");
      out.write("//            }\r\n");
      out.write("//        }\r\n");
      out.write("//    }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deleteClick(th) {\r\n");
      out.write("    var contents = $(th).parent().parent().find('td[contente=true]');\r\n");
      out.write("    if (contents[1].lastChild.value.trim().length > 0) {\r\n");
      out.write("        $(\"#dialog-confirm-delete-current-labtest\").data('contents', contents).dialog(\"open\");\r\n");
      out.write("    } else {\r\n");
      out.write("        deleteCurrentLabTestRow(contents);\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("function addClick() {\r\n");
      out.write("\r\n");
      out.write("    $(\"#dialog-f\").dialog(\"open\");\r\n");
      out.write("    $(\"#dialog-f\").find(\":checkbox:checked\");\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    var arrayCheckedLabTest = $(\"#dialog-f\").find(\":checkbox\");\r\n");
      out.write("    for (var i = 0; i < arrayCheckedLabTest.length; i++) {\r\n");
      out.write("//        $(\"#\" + currentLabTestWithValueArray[j].id + \"-current-labtest-value\").val();\r\n");
      out.write("        var labtestId=arrayCheckedLabTest[i].id.split(\"-\")[0];\r\n");
      out.write("        $(\"#\" +labtestId+\"-current-labtest-value\").val(\"\");\r\n");
      out.write("        arrayCheckedLabTest[i].checked = false;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("var addNotShowLabTest = [];\r\n");
      out.write("function initCurrentLabtestSelect2(deleteId, addId) {\r\n");
      out.write("    var url=window.location.href;\r\n");
      out.write("     var isEditMode=false;\r\n");
      out.write("     if(url.indexOf(\"null\")==-1){\r\n");
      out.write("     isEditMode=true;\r\n");
      out.write("     }\r\n");
      out.write("    var urlLoadOperation = \"clinic/medicaltest/medicalTest/loadCurrentMedicalTestChildWithoutMine\";\r\n");
      out.write("    if(isEditMode==true){\r\n");
      out.write("     urlLoadOperation+='/'+'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${visitId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\r\n");
      out.write("     }\r\n");
      out.write("    var preload_data_labtest;\r\n");
      out.write("\r\n");
      out.write("    $.getJSON(\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" + urlLoadOperation, function (data) {\r\n");
      out.write("\r\n");
      out.write("        preload_data_labtest = data;\r\n");
      out.write("//        currentOperationpreload_data = data;\r\n");
      out.write("//        currentOperationMultiSelectFD=data;\r\n");
      out.write("\r\n");
      out.write("        var preload_data2 = [];\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        if (deleteId != undefined) {\r\n");
      out.write("\r\n");
      out.write("            addNotShowLabTest.push({ComboID:addId, ComboCaption:deleteId});\r\n");
      out.write("\r\n");
      out.write("            $.each(addNotShowLabTest, function () {\r\n");
      out.write("\r\n");
      out.write("                preload_data_labtest.push({ComboID:this.ComboID, ComboCaption:this.ComboCaption });\r\n");
      out.write("\r\n");
      out.write("            });\r\n");
      out.write("        }\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        $.each(preload_data_labtest, function () {\r\n");
      out.write("\r\n");
      out.write("            preload_data2.push({id:this.ComboID, text:this.ComboCaption });\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        $('#p-labtestMultiSelect-current').select2({\r\n");
      out.write("            multiple:true,\r\n");
      out.write("            query:function (query) {\r\n");
      out.write("                var data = {results:[]};\r\n");
      out.write("\r\n");
      out.write("                $.each(preload_data_labtest, function () {\r\n");
      out.write("                    if (query.term.length == 0 || this.ComboCaption.toUpperCase().indexOf(query.term.toUpperCase()) >= 0) {\r\n");
      out.write("                        data.results.push({id:this.ComboID, text:this.ComboCaption });\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("\r\n");
      out.write("                query.callback(data);\r\n");
      out.write("            },\r\n");
      out.write("            createSearchChoice:function (term, data) {\r\n");
      out.write("                if ($(data).filter(\r\n");
      out.write("                        function () {\r\n");
      out.write("                            return this.text.localeCompare(term) === 0;\r\n");
      out.write("                        }).length === 0) {\r\n");
      out.write("                    return {id:term + '-newMehrsysLabtest', text:term};\r\n");
      out.write("                }\r\n");
      out.write("            }, initSelection:function (element, callback) {\r\n");
      out.write("                if (element.val() == \"-1\") {\r\n");
      out.write("                    element.val(\"\");\r\n");
      out.write("                    return;\r\n");
      out.write("                }\r\n");
      out.write("                var data = [];\r\n");
      out.write("                $(element.val().split(\",\")).each(function () {\r\n");
      out.write("                    for (var i = 0; i < preload_data2.length; i++) {\r\n");
      out.write("                        if (this != \"-1\") {\r\n");
      out.write("                            if (this == preload_data2[i].id) {\r\n");
      out.write("\r\n");
      out.write("                                data.push({id:this, text:preload_data2[i].text});\r\n");
      out.write("                            }\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                callback(data);\r\n");
      out.write("            },\r\n");
      out.write("            data:preload_data2\r\n");
      out.write("        });\r\n");
      out.write("        deleteCurrentLabTestOption(deleteId);\r\n");
      out.write("        selectCurrentLabtestOption(addId);\r\n");
      out.write("\r\n");
      out.write("         if(initCurrentLabState==true){\r\n");
      out.write("         $(\"#p-labtestMultiSelect-current\").select2('val', selectCurrentLabTestArrayElement);\r\n");
      out.write("             initCurrentLabState=false;\r\n");
      out.write("         }\r\n");
      out.write("\r\n");
      out.write("        $('#p-labtestMultiSelect-current').on(\"select2-removed\", function (e) {\r\n");
      out.write("\r\n");
      out.write("            if ($(\"#\" + e.choice.id).val().trim().length > 0) {\r\n");
      out.write("                $(\"#dialog-confirm-delete-current-labtest\").data('e', e).dialog(\"open\");\r\n");
      out.write("            } else {\r\n");
      out.write("                if ($('#' + e.choice.id + '-row').length > 0) {\r\n");
      out.write("                    $('#' + e.choice.id + '-row').remove();\r\n");
      out.write("                    var arrayCheckBox = $(\"#dialog-f\").find(\":checkbox:checked\");\r\n");
      out.write("                    for (var i = 0; i < arrayCheckBox.length; i++) {\r\n");
      out.write("                        if (arrayCheckBox[i].id == e.choice.id) {\r\n");
      out.write("                            $(\"#\" + e.choice.id).attr('checked', false);\r\n");
      out.write("                            $(\"#\" + e.choice.id).prop('checked', false);\r\n");
      out.write("                        }\r\n");
      out.write("                    }\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        $('#p-labtestMultiSelect-current').on(\"select2-selecting\", function (e) {\r\n");
      out.write("            var id = \"\" + e.object.id;\r\n");
      out.write("            if (id.indexOf('-newMehrsysLabtest') == -1) {\r\n");
      out.write("                addLabTestToTableAndSelectCheckBox(e.object.id, e.object.text);\r\n");
      out.write("            } else {//should save on db\r\n");
      out.write("                e.object.id = e.object.id.split('-newMehrsysLabtest')[0];\r\n");
      out.write("                var areUShureAddOperation = \"");
      out.print(areUShureAddLabTest);
      out.write("\";\r\n");
      out.write("                var newItemArray = [];\r\n");
      out.write("                newItemArray[0] = e.object.text;\r\n");
      out.write("                newItemArray[1] = e.object.id;\r\n");
      out.write("                $(\"#dialog-confirm-save-current-labtest\").data('newItemArray', newItemArray).dialog('open');\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        });\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function addLabTestToTableAndSelectCheckBox(labTestId, labTestText) {\r\n");
      out.write("    if (labTestId == labTestText) {\r\n");
      out.write("        return;\r\n");
      out.write("    }\r\n");
      out.write("    var currentLabTestOrderWithValueArray = $('#table').parent().find('textarea');\r\n");
      out.write("    var found = false;\r\n");
      out.write("    for (var i = 0; i < currentLabTestOrderWithValueArray.length; i++) {\r\n");
      out.write("        if (currentLabTestOrderWithValueArray[i].id == labTestId || currentLabTestOrderWithValueArray[i].id == labTestText) {\r\n");
      out.write("            found = true;\r\n");
      out.write("            break;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    rowNumber++;\r\n");
      out.write("    if (found == false) {\r\n");
      out.write("        $('#table').append('<tr id=\"' + labTestId + '-'+rowNumber+'-row' + '\"></td>' +\r\n");
      out.write("        '<td contente=\"true\">' + labTestText + '</td>' +\r\n");
      out.write("        '<td contente=\"true\"> <textarea  onkeyup=\"textArea_onKeyUp(this)\" id=\"' + labTestId +'-'+rowNumber+ '\" style=\" width: 100%;resize: none; \"/></td>' +\r\n");
      out.write("        '<td contente=\"true\"><input type=\"text\" id=\"'+labTestId+'-'+rowNumber+'-labtest-current-date\" value=\"");
      out.print(curStringDate);
      out.write("\" class=\"uk-width-1-1 currentLabtestDatePicker\" style=\"width: 100px; text-align: center;\"/></td>' +\r\n");
      out.write("        '<td><input type=\"button\" value=\"delete\"  class=\"uk-button-mini uk-button-danger\" onclick=\"deleteClick(this)\" /></td>' +\r\n");
      out.write("        '<td><input type=\"checkbox\" id=\"'+labTestId+'-'+rowNumber+'-currentLabtest-checkbox-highlight'+'\"</td></tr>' + '');\r\n");
      out.write("    }\r\n");
      out.write("    $(\"#\" + labTestId + \"-current-labtest-checkbox\").attr('checked', true);\r\n");
      out.write("    $(\"#\" + labTestId + \"-current-labtest-checkbox\").prop('checked', true);\r\n");
      out.write("    enableSaveLabTestItemBtnAndAddToLabTestReportBtn();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function selectCurrentLabtestOption(id) {\r\n");
      out.write("    var labTestIdSelect2Array = $(\"#p-labtestMultiSelect-current\").select2('val');\r\n");
      out.write("    labTestIdSelect2Array[labTestIdSelect2Array.length] = id;\r\n");
      out.write("    $(\"#p-labtestMultiSelect-current\").select2('val', labTestIdSelect2Array);\r\n");
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("$(currentLabTestCheckboxEventHandler());\r\n");
      out.write("function currentLabTestCheckboxEventHandler(){\r\n");
      out.write("\t$(\"input[id*='-currentLabtest-checkbox-highlight']\").change(function() {\r\n");
      out.write("\t\tenableSaveLabTestItemBtnAndAddToLabTestReportBtn();\r\n");
      out.write("\t});\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function enableSaveLabTestItemBtnAndAddToLabTestReportBtn(){\r\n");
      out.write("\t$(\"#saveLabTestItemBtn\").removeAttr(\"disabled\");\r\n");
      out.write("\t$(\"#addToLabTestReportBtn\").removeAttr(\"disabled\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function saveLabTestItem(){\r\n");
      out.write("\t$(\"#saveLabTestItemBtn\").attr(\"disabled\",\"disabled\");\r\n");
      out.write("\tcurrentLabTestCheckboxEventHandler();\r\n");
      out.write("\t//\r\n");
      out.write("\tvar data = {};\r\n");
      out.write("\tdata.visitQueueId = \"");
      out.print(visitQueueId);
      out.write("\";\r\n");
      out.write("\tdata.visitId = cuVisitId;\r\n");
      out.write("\t\r\n");
      out.write("    var currentLabTestWithValueArray = $(\"#table\").parent().find(\"textarea\");\r\n");
      out.write("    var currentLabTestWithValueMap = {};\r\n");
      out.write("    \r\n");
      out.write("    if(currentLabTestWithValueArray.length > 0){\r\n");
      out.write("        for(var w=0; w<currentLabTestWithValueArray.length; w++){\r\n");
      out.write("            var value = [];\r\n");
      out.write("            value[0] = currentLabTestWithValueArray[w].value;\r\n");
      out.write("//            value[1] = $(\"#\"+currentLabTestWithValueArray[w].id + \"-currentLabtest-checkbox-highlight\").prop(\"checked\");\r\n");
      out.write("            value[1] = $(\"#table\").parent().find(\"input:checkbox\")[w].checked;\r\n");
      out.write("            value[2] = $(\"#table\").parent().find(\"input:text\")[w].value;\r\n");
      out.write("//            $(\"#table\").parent().find(\"input:text\")[0].value\r\n");
      out.write("            currentLabTestWithValueMap[currentLabTestWithValueArray[w].id] = value;\r\n");
      out.write("        }\r\n");
      out.write("        data.currentLabTestWithValueMap = currentLabTestWithValueMap;\r\n");
      out.write("    }\r\n");
      out.write("    //\r\n");
      out.write("    $.ajax({\r\n");
      out.write("        url: \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" + \"/clinic/patient/visitMobileBase/saveLabTestItem/\",\r\n");
      out.write("        contentType: \"application/json; charset=utf-8\",\r\n");
      out.write("        data: JSON.stringify(data),\r\n");
      out.write("        dataType: \"json\",\r\n");
      out.write("        type: \"POST\",\r\n");
      out.write("        success: function (data, success, xhr) {\r\n");
      out.write("            alertify.success(data.message);\r\n");
      out.write("            //\r\n");
      out.write("            cuVisitId = data.backVisitId;\r\n");
      out.write("            //\r\n");
      out.write("        \temptyPatientFile();\r\n");
      out.write("        \tloadPatientFile();\r\n");
      out.write("        \t//\r\n");
      out.write("        },\r\n");
      out.write("        error: function (e) {\r\n");
      out.write("            alert(\"Error In Saving Lab Test Item: \" + e.responseText);\r\n");
      out.write("        }\r\n");
      out.write("    });\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function addToLabTestReport(){\r\n");
      out.write("\talertify.success(\"New Lab Test Item(s) Added To Report\");\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<style scoped>\r\n");
      out.write("    .demo-section {\r\n");
      out.write("        width: 605px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .product-view {\r\n");
      out.write("        float: left;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        width: 301px;\r\n");
      out.write("        margin: -1px -1px 0 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .product-view dl {\r\n");
      out.write("        margin: 10px 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        min-width: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .product-view dt, dd {\r\n");
      out.write("        float: left;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 3px;\r\n");
      out.write("        height: 26px;\r\n");
      out.write("        width: 160px;\r\n");
      out.write("        line-height: 26px;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .product-view dt {\r\n");
      out.write("        clear: left;\r\n");
      out.write("        padding: 3px 5px 3px 0;\r\n");
      out.write("        text-align: right;\r\n");
      out.write("        opacity: 0.6;\r\n");
      out.write("        width: 100px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .k-listview {\r\n");
      out.write("        border: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        min-width: 605px;\r\n");
      out.write("        min-height: 298px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .k-listview:after, .product-view dl:after {\r\n");
      out.write("        content: \".\";\r\n");
      out.write("        display: block;\r\n");
      out.write("        height: 0;\r\n");
      out.write("        clear: both;\r\n");
      out.write("        visibility: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .edit-buttons {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: 0;\r\n");
      out.write("        right: 0;\r\n");
      out.write("        width: 26px;\r\n");
      out.write("        height: 146px;\r\n");
      out.write("        padding: 2px 2px 0 3px;\r\n");
      out.write("        background-color: rgba(0, 0, 0, 0.1);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .edit-buttons .k-button {\r\n");
      out.write("        width: 26px;\r\n");
      out.write("        margin-bottom: 1px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .k-pager-wrap {\r\n");
      out.write("        border-top: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    span.k-invalid-msg {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        margin-left: 6px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .Table {\r\n");
      out.write("        display: table;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .Title {\r\n");
      out.write("        display: table-caption;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        font-size: larger;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .Heading {\r\n");
      out.write("        display: table-row;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .Row {\r\n");
      out.write("        display: table-row;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .Cell {\r\n");
      out.write("        display: table-cell;\r\n");
      out.write("        border: solid;\r\n");
      out.write("        border-width: thin;\r\n");
      out.write("        padding-left: 5px;\r\n");
      out.write("        padding-right: 5px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("\t#dialog-f label.hasFocus, #dialog-f+div button:focus {\r\n");
      out.write("\t\tcolor: #00a8e6 !important;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t#dialog-f textarea:focus {\r\n");
      out.write("\t\tborder: 1px solid #00a8e6 !important;\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\ttextarea {\r\n");
      out.write("\t\theight: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/pages/clinic/patient/ConfigurablePatientRecord/fileBaseItems/CurrentLabTestAndResult.jsp(682,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }
}
