/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2018-01-15 15:49:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.clinic.patient.VisitMobileBase.fileBaseItems;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.List;
import com.artonis.clinic.core.model.MedicalTest;
import java.util.ArrayList;
import com.artonis.clinic.customize.view.UserLabTestItemView;

public final class LabTestOrder_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1484491107000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/matab/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323245778000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.artonis.clinic.customize.view.UserLabTestItemView");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.artonis.clinic.core.model.MedicalTest");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div>\n");
      out.write("    ");
      out.write("\n");
      out.write("    ");
      out.write("\n");
      out.write("    <input type=\"hidden\" id=\"p-allLabTest\" style=\"direction:ltr; width: 100%; height:100% \"/>\n");
      out.write("</div>\n");

    List<String> idClassRemoveList = new ArrayList<String>();

      out.write("\n");
      out.write("<div>\n");
      out.write("\t<select id=\"labTestOrders_customized\" multiple=\"multiple\"></select>\n");
      out.write("    <button name=\"customizedLabTest\" id=\"customizedLabTest\" onclick=\"customizedLabTestClick()\">select customized LabTest\n");
      out.write("    </button>\n");
      out.write("</div>\n");
      out.write("<div id=\"dialog-customizeLabtest\" title='select lab test' style=\"display:none;direction: ltr;height: 100% !important;\">\n");
      out.write("    <form class=\"toPopup\" style=\"direction: ltr\">\n");
      out.write("        ");

            int column = 5;
            List<UserLabTestItemView> userLabTestList = (List<UserLabTestItemView>) request.getAttribute("userLabTestList");
            int index = 0;
            Long currentCoding = 0L;
            Long subCurrentCoding = 0L;
            Long previousCoding = 0L;
            if(userLabTestList==null || userLabTestList.size()==0){
                
      out.write("<table>");

            }
            for (UserLabTestItemView userLabTestItemView : userLabTestList) {
                currentCoding=userLabTestItemView.getUser_labtest_id();
                if (index == 0) {
                  if(currentCoding!=null){
                      previousCoding=currentCoding;
                  }
        
      out.write("\n");
      out.write("        <table>\n");
      out.write("            <tr id=\"all-select-order-labtest\">\n");
      out.write("                <td>\n");
      out.write("                    <input type=\"checkbox\" id=\"all-select-order-labtest-checkbox\"\n");
      out.write("                           name=\"all-select-order-labtest-checkbox\"\n");
      out.write("                           onclick=\"selectAllOrderLabTestCheckBox(this)\"/>\n");
      out.write("                    <label for=\"all-select-order-labtest-checkbox\">select all\n");
      out.write("                    </label>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            <tr style=\"background-color: #9cf;\">\n");
      out.write("\n");
      out.write("               ");
      out.write("\n");
      out.write("               <td>\n");
      out.write("\n");
      out.write("\n");
      out.write("                   <input type=\"checkbox\" name=\"");
      out.print(userLabTestItemView.getName());
      out.write("\"  onclick=\"groupSelect(this)\"\n");
      out.write("                          id=\"");
      out.print(userLabTestItemView.getName());
      out.write("-group-customize\"/>\n");
      out.write("                   ");
      out.write("\n");
      out.write("                   <label for=\"");
      out.print(userLabTestItemView.getName());
      out.write("-group-customize\"><span style=\"font-weight:bold\">");
      out.print(userLabTestItemView.getName());
      out.write("</span>\n");
      out.write("                   </label>\n");
      out.write("               </td>\n");
      out.write("               <td></td>\n");
      out.write("               <td></td>\n");
      out.write("               <td></td>\n");
      out.write("               <td></td>\n");
      out.write("            </tr>\n");
      out.write("            ");
      out.write("\n");
      out.write("            <tr id=\"order-labtest-coding-");
      out.print(currentCoding);
      out.write("\" >\n");
      out.write("                <td>\n");
      out.write("\n");
      out.write("                    <input type=\"checkbox\" name=\"");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\"\n");
      out.write("                           id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-customize\" groupName=\"");
      out.print(userLabTestItemView.getName());
      out.write("\"/>\n");
      out.write("                           ");
      out.write("\n");
      out.write("                        <label for=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-customize\">");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\n");
      out.write("                        </label>\n");
      out.write("                </td>\n");
      out.write("                ");

                } else if ((previousCoding==null &&currentCoding!=null)||
                        (previousCoding!=null &&currentCoding==null) ||
                        ((previousCoding!=null &&currentCoding!=null) && !previousCoding.equals(currentCoding))) {
                    previousCoding = currentCoding;
                    subCurrentCoding=0L;
                    int def = 0;
                    if (index % column != 0) {
                        def = column - (index % column);
                        index += column - (index % column);
                        if (def > 0) {
                            for (int j = 0; j < def; j++) {
      out.write("\n");
      out.write("                <td>&nbsp;</td>\n");
      out.write("                ");

                            }
                        }

                    }
                
      out.write("\n");
      out.write("            </tr>\n");
      out.write("            <tr style=\"background-color: #9cf;\">\n");
      out.write("                <td >\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <input type=\"checkbox\" name=\"");
      out.print(userLabTestItemView.getName());
      out.write("\" onclick=\"groupSelect(this)\"\n");
      out.write("                           id=\"");
      out.print(userLabTestItemView.getName());
      out.write("-group-customize\"/>\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    <label for=\"");
      out.print(userLabTestItemView.getName());
      out.write("-group-customize\"><span style=\"font-weight:bold\">");
      out.print(userLabTestItemView.getName());
      out.write("</span>\n");
      out.write("                    </label>\n");
      out.write("                </td>\n");
      out.write("                <td></td>\n");
      out.write("                <td></td>\n");
      out.write("                <td></td>\n");
      out.write("                <td></td>\n");
      out.write("            </tr>\n");
      out.write("            ");
      out.write("\n");
      out.write("            <tr id=\"order-labtest-coding-");
      out.print(currentCoding);
      out.write("\" >\n");
      out.write("                <td>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <input type=\"checkbox\" name=\"");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\"\n");
      out.write("                           id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-customize\" groupName=\"");
      out.print(userLabTestItemView.getName());
      out.write("\"/>\n");
      out.write("                    ");
      out.write("\n");
      out.write("                    <label for=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-customize\">");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\n");
      out.write("                    </label>\n");
      out.write("                </td>\n");
      out.write("\n");
      out.write("            ");

                    } else if (index % column == 0) {
                         String trId="";
                         if(subCurrentCoding==0){
                            subCurrentCoding++;
                            trId=String.valueOf(currentCoding)+"_"+String.valueOf(subCurrentCoding);
                            idClassRemoveList.add(String.valueOf(currentCoding));
                         }else {
                            subCurrentCoding++;
                            trId=String.valueOf(currentCoding)+"_"+String.valueOf(subCurrentCoding);
                            idClassRemoveList.add(String.valueOf(currentCoding)+"_"+String.valueOf(subCurrentCoding-1));

                         }
                    
      out.write("\n");
      out.write("            ");
      out.write("\n");
      out.write("            <tr id=\"order-labtest-coding-");
      out.print(trId);
      out.write("\">\n");
      out.write("                <td>\n");
      out.write("                    ");
      out.write("\n");
      out.write("\n");
      out.write("                    <input type=\"checkbox\" name=\"");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\"\n");
      out.write("                           id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-customize\" groupName=\"");
      out.print(userLabTestItemView.getName());
      out.write("\"/>\n");
      out.write("                           ");
      out.write("\n");
      out.write("                        <label for=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-customize\">");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\n");
      out.write("                        </label>\n");
      out.write("                </td>\n");
      out.write("                ");

                } else if (index % column != 0 && index % column != column - 1) {
                
      out.write("\n");
      out.write("                <td>\n");
      out.write("                    ");
      out.write("\n");
      out.write("\n");
      out.write("                    <input type=\"checkbox\" name=\"");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\"\n");
      out.write("                           id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-customize\" groupName=\"");
      out.print(userLabTestItemView.getName());
      out.write("\"/>\n");
      out.write("                           ");
      out.write("\n");
      out.write("                    <label for=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-customize\">");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\n");
      out.write("                    </label>\n");
      out.write("                </td>\n");
      out.write("                ");

                } else if (index % column == column - 1) {
                
      out.write("\n");
      out.write("                <td>\n");
      out.write("                    ");
      out.write("\n");
      out.write("\n");
      out.write("                    <input type=\"checkbox\" name=\"");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\"\n");
      out.write("                           id=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-customize\" groupName=\"");
      out.print(userLabTestItemView.getName());
      out.write("\"/>\n");
      out.write("                           ");
      out.write("\n");
      out.write("                    <label for=\"");
      out.print(userLabTestItemView.getMedicalTest_id().toString());
      out.write("-customize\">");
      out.print(userLabTestItemView.getMedicalTestName());
      out.write("\n");
      out.write("                    </label>\n");
      out.write("                </td>\n");
      out.write("            </tr>\n");
      out.write("            ");

                    }
                    index++;
                }

                if(subCurrentCoding==0){
                    idClassRemoveList.add(String.valueOf(currentCoding));
                }else {
                    idClassRemoveList.add(String.valueOf(currentCoding)+"_"+String.valueOf(subCurrentCoding));
                }
            
      out.write("\n");
      out.write("        </table>\n");
      out.write("    </form>\n");
      out.write("</div>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("function onClickCheckBoxLabTestOrder(){\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("function selectAllOrderLabTestCheckBox(e) {\n");
      out.write("    var checkBoxElementArray = $(\"#dialog-customizeLabtest\").find(\":checkbox\");\n");
      out.write("    for (var i = 1; i < checkBoxElementArray.length; i++) {\n");
      out.write("        checkBoxElementArray[i].checked = e.checked;\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function cbcSelect(e){\n");
      out.write("    $(\"#2-customize\").attr('checked',e.checked);\n");
      out.write("    $(\"#2-customize\").prop('checked',e.checked);\n");
      out.write("    $(\"#480-customize\").attr('checked',e.checked);\n");
      out.write("    $(\"#480-customize\").prop('checked',e.checked);\n");
      out.write("    $(\"#14-customize\").attr('checked',e.checked);\n");
      out.write("    $(\"#14-customize\").prop('checked',e.checked);\n");
      out.write("    $(\"#6-customize\").attr('checked',e.checked);\n");
      out.write("    $(\"#6-customize\").prop('checked',e.checked);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function groupSelect(e){\n");
      out.write("/*\n");
      out.write("    ");
 for (UserLabTestItemView userLabTestItemView : userLabTestList)  {
        String groupName=userLabTestItemView.getName();
      out.write("\n");
      out.write("        if(e.name=='");
      out.print(groupName);
      out.write("' && $(\"#\"+\"");
      out.print(userLabTestItemView.getMedicalTest_id());
      out.write("\"+\"-customize\")[0].attributes[\"groupname\"].childNodes[0].data==\"");
      out.print(userLabTestItemView.getName());
      out.write("\"){\n");
      out.write("            $(\"#\"+\"");
      out.print(userLabTestItemView.getMedicalTest_id());
      out.write("\"+\"-customize\").attr('checked',e.checked);\n");
      out.write("            $(\"#\"+\"");
      out.print(userLabTestItemView.getMedicalTest_id());
      out.write("\"+\"-customize\").prop('checked',e.checked);\n");
      out.write("        }\n");
      out.write("    ");
} 
      out.write("\n");
      out.write("*/\n");
      out.write("\t$('#dialog-customizeLabtest input[groupname=' + e.name + ']').prop('checked', e.checked);\n");
      out.write("}\n");
      out.write("\n");
      out.write("var allLabTestFD = {};\n");
      out.write("var labTestList = new Array();\n");
      out.write("$(document).ready(function () {\n");
      out.write("    ");
      out.write("\n");
      out.write("    /*var listIdClassRemoveOrder=[];\n");
      out.write("    ");
 for (int i=0; i<idClassRemoveList.size(); i++) { 
      out.write("\n");
      out.write("        $(\"#order-labtest-coding-\" + \"");
      out.print( idClassRemoveList.get(i) );
      out.write("\").removeClass();\n");
      out.write("    ");
 } 
      out.write("*/\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    var url=window.location.href;\n");
      out.write("    var isEditMode=false;\n");
      out.write("    if(url.indexOf(\"null\")==-1){\n");
      out.write("        isEditMode=true;\n");
      out.write("    }\n");
      out.write("    var urlLoadOrderLabTest = \"clinic/medicaltest/medicalTest/loadMedicalTestChildWithoutMine\";\n");
      out.write("    if(isEditMode==true){\n");
      out.write("        urlLoadOrderLabTest+='/'+'");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${visitId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("';\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    var preload_data_labtest;\n");
      out.write("\n");
      out.write("    $.getJSON(\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" + urlLoadOrderLabTest, function (data) {\n");
      out.write("\n");
      out.write("        preload_data_labtest = data;\n");
      out.write("        allLabTestFD = data;\n");
      out.write("        var preload_data2 = [];\n");
      out.write("\n");
      out.write("        $.each(preload_data_labtest, function () {\n");
      out.write("\n");
      out.write("            preload_data2.push({id:this.ComboID, text:this.ComboCaption });\n");
      out.write("\n");
      out.write("        });\n");
      out.write("\n");
      out.write("        $('#p-allLabTest').select2({\n");
      out.write("            multiple:true,\n");
      out.write("            query:function (query) {\n");
      out.write("                var data = {results:[]};\n");
      out.write("\n");
      out.write("                $.each(preload_data_labtest, function () {\n");
      out.write("                    if (query.term.length == 0 || this.ComboCaption.toUpperCase().indexOf(query.term.toUpperCase()) >= 0) {\n");
      out.write("                        data.results.push({id:this.ComboID, text:this.ComboCaption });\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("\n");
      out.write("                query.callback(data);\n");
      out.write("            },\n");
      out.write("            createSearchChoice:function (term, data) {\n");
      out.write("                if ($(data).filter(\n");
      out.write("                        function () {\n");
      out.write("                            return this.text.localeCompare(term) === 0;\n");
      out.write("                        }).length === 0) {\n");
      out.write("                    return {id:term, text:term};\n");
      out.write("                }\n");
      out.write("            }, initSelection:function (element, callback) {\n");
      out.write("                if (element.val() == \"-1\") {\n");
      out.write("                    element.val(\"\");\n");
      out.write("                    return;\n");
      out.write("                }\n");
      out.write("                var data = [];\n");
      out.write("                $(element.val().split(\",\")).each(function () {\n");
      out.write("                    for (var i = 0; i < preload_data2.length; i++) {\n");
      out.write("                        if (this != \"-1\") {\n");
      out.write("                            if (this == preload_data2[i].id) {\n");
      out.write("                                data.push({id:this, text:preload_data2[i].text});\n");
      out.write("                            }\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                });\n");
      out.write("\n");
      out.write("\n");
      out.write("                callback(data);\n");
      out.write("            },\n");
      out.write("            data:preload_data2\n");
      out.write("        });\n");
      out.write("\n");
      out.write("\n");
      out.write("//            for ( var i = 0; i < data.length; i++) {\n");
      out.write("//                $(\"#p-allLabTest\").append(\n");
      out.write("//                        \"<option style='direction:ltr' value='\" + data[i].ComboID + \"' >\" + data[i].ComboCaption + \"</option>\")\n");
      out.write("//            }\n");
      out.write("        $(\"#p-allLabTest\").select2('val', ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${labTestIds}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(");\n");
      out.write("\n");
      out.write("\n");
      out.write("        ");

           if(!request.getAttribute("labTestIds").toString().equals("-1")){


           List<String> list = (List)request.getAttribute("labTestIds");
           if(list!=null){
           for(int count=0; count <list.size(); count++) {
        
      out.write("\n");
      out.write("        labTestList[");
      out.print( count );
      out.write("] = '");
      out.print( list.get(count) );
      out.write("';\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        ");
 } 
      out.write("\n");
      out.write("        var allcustomizeLabtest=$(\"#dialog-customizeLabtest\").find(\":checkbox\");\n");
      out.write("        i = 0, size = labTestList.length;\n");
      out.write("        for (i; i < size; i++) {\n");
      out.write("            $(\"#labTestOrders_customized\").multiselect(\"widget\").find(\":checkbox[value='\" + labTestList[i] + \"']\").attr(\"checked\", \"checked\");\n");
      out.write("            $(\"#labTestOrders_customized option[value='\" + labTestList[i] + \"']\").attr(\"selected\", 1);\n");
      out.write("\n");
      out.write("            for(z=0;z<allcustomizeLabtest.length;z++){\n");
      out.write("                if(labTestList[i]==allcustomizeLabtest[z].id.split('-customize')[0]){\n");
      out.write("                    allcustomizeLabtest[z].checked=true;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("        $(\"#labTestOrders_customized\").multiselect(\"refresh\");\n");
      out.write("        var size = $(\".ui-multiselect\").size();\n");
      out.write("        for (var i = 0; i < size; i++) {\n");
      out.write("            $(\".ui-multiselect\")[i].style.width = \"65%\";\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        $(\".ui-multiselect-menu\").css(\"width\", '70%');\n");
      out.write("\n");
      out.write("    });\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    var cancelButtenLabTestOrderClick=false;\n");
      out.write("    $(\"#dialog-customizeLabtest\").dialog({\n");
      out.write("        autoOpen:false,\n");
      out.write("        show:{\n");
      out.write("            effect:\"slide\",\n");
      out.write("            duration:300\n");
      out.write("        },\n");
      out.write("        hide:{\n");
      out.write("            effect:\"slide\",\n");
      out.write("            duration:300\n");
      out.write("        },\n");
      out.write("        height:800,\n");
      out.write("        width:800,\n");
      out.write("        modal:true,\n");
      out.write("        buttons:{\n");
      out.write("            \"ok\":function () {\n");
      out.write("                popUpLabTestOrderOkButton();\n");
      out.write("\n");
      out.write("                $(this).dialog(\"close\");\n");
      out.write("\n");
      out.write("            },\n");
      out.write("            \"cancel\":function () {\n");
      out.write("                cancelButtenLabTestOrderClick=true;\n");
      out.write("                $(this).dialog(\"close\");\n");
      out.write("            }\n");
      out.write("        },\n");
      out.write("        close:function (event, ui ) {\n");
      out.write("            if(event.which!=undefined || cancelButtenLabTestOrderClick==true){\n");
      out.write("                cancelEventLabTestOrder();\n");
      out.write("              cancelButtenLabTestOrderClick=false;\n");
      out.write("            }\n");
      out.write("            $(this).dialog(\"close\");\n");
      out.write("        },\n");
      out.write("        open:function (event, ui) {\n");
      out.write("            arrayCheckedBoxBeforeOpenedLabTestOrder=$(\"#dialog-customizeLabtest\").find(\":checkbox:checked\");\n");
      out.write("\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    jQuery('body')\n");
      out.write("            .bind(\n");
      out.write("            'click',\n");
      out.write("            function (e) {\n");
      out.write("                if (\n");
      out.write("                        jQuery('#dialog-customizeLabtest').dialog('isOpen')\n");
      out.write("                                && !jQuery(e.target).is('.ui-dialog, a')\n");
      out.write("                                && !jQuery(e.target).closest('.ui-dialog').length\n");
      out.write("                                && event.target.nodeName!=\"BUTTON\"\n");
      out.write("                        ) {\n");
      out.write("                    popUpLabTestOrderOkButton();\n");
      out.write("                    jQuery('#dialog-customizeLabtest').dialog('close');\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("    );\n");
      out.write("\n");
      out.write("});\n");
      out.write("var arrayCheckedBoxBeforeOpenedLabTestOrder;\n");
      out.write("function cancelEventLabTestOrder(){\n");
      out.write("    arrayCheckedBoxAfterCancel=$(\"#dialog-customizeLabtest\").find(\":checkbox:checked\");\n");
      out.write("    for(var i=0;i<arrayCheckedBoxAfterCancel.length;i++){\n");
      out.write("        $(\"#\"+arrayCheckedBoxAfterCancel[i].id).attr('checked',false);\n");
      out.write("        $(\"#\"+arrayCheckedBoxAfterCancel[i].id).prop('checked',false);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    for(var j=0;j<arrayCheckedBoxBeforeOpenedLabTestOrder.length;j++){\n");
      out.write("        $(\"#\"+arrayCheckedBoxBeforeOpenedLabTestOrder[j].id).attr('checked',true);\n");
      out.write("        $(\"#\"+arrayCheckedBoxBeforeOpenedLabTestOrder[j].id).prop('checked',true);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("\n");
      out.write("}\n");
      out.write("\n");
      out.write("function popUpLabTestOrderOkButton(){\n");
      out.write("    var arrayCheckedLabTest = $(\"#dialog-customizeLabtest\").find(\":checkbox:checked\");\n");
      out.write("    var selectedLabTestInComboArray = $(\"#labTestOrders_customized\").val();\n");
      out.write("    if ($(\"#labTestOrders_customized\").val() != null) {\n");
      out.write("\n");
      out.write("        for (var j = 0; j < selectedLabTestInComboArray.length; j++) {\n");
      out.write("            var found = false;\n");
      out.write("            for (var index = 0; index < arrayCheckedLabTest.length; index++) {\n");
      out.write("\n");
      out.write("                if (arrayCheckedLabTest[index].id.split('-customize')[0] == selectedLabTestInComboArray[j]) {\n");
      out.write("                    found = true;\n");
      out.write("                    break;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("            if (found == false) {\n");
      out.write("\n");
      out.write("                $(\"#labTestOrders_customized\").multiselect(\"widget\").find(\":checkbox[value='\" +selectedLabTestInComboArray[j] + \"']\").attr(\"checked\", \"false\");\n");
      out.write("                $(\"#labTestOrders_customized option[value='\" + selectedLabTestInComboArray[j] + \"']\").attr(\"selected\", false);\n");
      out.write("//                $(\"#labTestOrders_customized\").multiselect(\"refresh\");\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("    for (var index = 0; index < arrayCheckedLabTest.length; index++) {\n");
      out.write("        var id = arrayCheckedLabTest[index].id.split('-customize')[0];\n");
      out.write("        $(\"#labTestOrders_customized\").multiselect(\"widget\").find(\":checkbox[value='\" + id + \"']\").attr(\"checked\", \"checked\");\n");
      out.write("        $(\"#labTestOrders_customized option[value='\" + id + \"']\").attr(\"selected\", 1);\n");
      out.write("    }\n");
      out.write("    $(\"#labTestOrders_customized\").multiselect(\"refresh\");\n");
      out.write("\n");
      out.write("    var size = $(\".ui-multiselect\").size();\n");
      out.write("    for (var i = 0; i < size; i++) {\n");
      out.write("        $(\".ui-multiselect\")[i].style.width = \"65%\";\n");
      out.write("    }\n");
      out.write("    $(\".ui-multiselect-menu\").css(\"width\", '70%');\n");
      out.write("}\n");
      out.write("function customizedLabTestClick() {\n");
      out.write("\n");
      out.write("    $(\"#dialog-customizeLabtest\").dialog(\"open\");\n");
      out.write("}\n");
      out.write("\n");
      out.write("function checkAllCustomizeLabTestEvent(event, ui){\n");
      out.write("    for(var i=0;i<event.target.length;i++){\n");
      out.write("        if($(\"#\"+event.target[i].value+\"-customize\").length>0){\n");
      out.write("            $(\"#\"+event.target[i].value+\"-customize\").attr('checked',true);\n");
      out.write("            $(\"#\"+event.target[i].value+\"-customize\").prop('checked',true);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function clickCustomizeLabTestEvent(event,ui){\n");
      out.write("    if(ui.checked==true){\n");
      out.write("        $(\"#\"+ui.value+\"-customize\").attr('checked',true)\n");
      out.write("        $(\"#\"+ui.value+\"-customize\").prop('checked',true)\n");
      out.write("    }else if(ui.checked==false){\n");
      out.write("        $(\"#\"+ui.value+\"-customize\").attr('checked',false)\n");
      out.write("        $(\"#\"+ui.value+\"-customize\").prop('checked',false)\n");
      out.write("    }\n");
      out.write("    console.log(ui);\n");
      out.write("}\n");
      out.write("\n");
      out.write("function optgrouptoggleCustomizeLabTestEvent(event,ui){\n");
      out.write("    for(var i=0;i<ui.inputs.length;i++){\n");
      out.write("        if($(\"#\"+ui.inputs[i].value+\"-customize\").length>0){\n");
      out.write("            $(\"#\"+ui.inputs[i].value+\"-customize\").attr('checked',ui.checked);\n");
      out.write("            $(\"#\"+ui.inputs[i].value+\"-customize\").prop('checked',ui.checked);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("function unCheckAllCustomizeLabTestEvent(event,ui){\n");
      out.write("    for(var i=0;i<event.target.length;i++){\n");
      out.write("        if($(\"#\"+event.target[i].value+\"-customize\").length>0){\n");
      out.write("            $(\"#\"+event.target[i].value+\"-customize\").attr('checked',false);\n");
      out.write("            $(\"#\"+event.target[i].value+\"-customize\").prop('checked',false);\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("}\n");
      out.write("\n");
      out.write("\n");
      out.write("var mapToArray = {};\n");
      out.write("$(\"#labTestOrders_customized2\").on(\"multiselectclick\", function (event, ui) {\n");
      out.write("\n");
      out.write("    isChecked = ui.checked;\n");
      out.write("    value = ui.value;\n");
      out.write("    var array;\n");
      out.write("\n");
      out.write("    array = $(\"#p-allLabTest\").select2('val');\n");
      out.write("    var arrayLength = array.length;\n");
      out.write("//        console.log(array);\n");
      out.write("    if (isChecked == false && value in mapToArray) {\n");
      out.write("        delete mapToArray[value];\n");
      out.write("    }\n");
      out.write("\n");
      out.write("\n");
      out.write("    $.getJSON(\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\" + \"clinic/customize/userLabTestGroup/loadLabTestGroupItem/\" + ui.value, function (data, ui) {\n");
      out.write("\n");
      out.write("//              for(var i=0;i<data.length;i++){\n");
      out.write("//                  $(\"#labTestOrders_customized\").multiselect(\"widget\").find(\":checkbox[value='\"+data[i]+\"']\").attr(\"checked\",\"checked\");\n");
      out.write("//                  $(\"#labTestOrders_customized option[value='\" + data[i] + \"']\").attr(\"selected\", 1);\n");
      out.write("//                  $(\"#labTestOrders_customized\").multiselect(\"refresh\");\n");
      out.write("//              }\n");
      out.write("        if (isChecked == true) {\n");
      out.write("            mapToArray[value] = data;\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        for (var i = 0; i < data.length; i++) {\n");
      out.write("\n");
      out.write("            $(\"#labTestOrders_customized\").multiselect(\"widget\").find(\":checkbox\").each(function () {\n");
      out.write("                if (this.value == data[i]) {\n");
      out.write("                    if (isChecked == true || this.checked == true) {\n");
      out.write("                        isFound = false;\n");
      out.write("                        for (var key in mapToArray) {\n");
      out.write("                            if (key == value) {\n");
      out.write("                                continue;\n");
      out.write("                            }\n");
      out.write("                            ar = mapToArray[key];\n");
      out.write("                            for (var j = 0; j < ar.length; j++) {\n");
      out.write("                                if (ar[j] == data[i]) {\n");
      out.write("                                    isFound = true;\n");
      out.write("                                    break;\n");
      out.write("                                }\n");
      out.write("                            }\n");
      out.write("                            if (isFound == true) {\n");
      out.write("                                break;\n");
      out.write("\n");
      out.write("                            }\n");
      out.write("\n");
      out.write("                        }\n");
      out.write("                        if (isFound == false) {\n");
      out.write("                            this.click();\n");
      out.write("                        }\n");
      out.write("\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("            if (isChecked == true) {\n");
      out.write("                array[arrayLength + i] = data[i];\n");
      out.write("            } else {\n");
      out.write("                isFound = false;\n");
      out.write("                for (var key in mapToArray) {\n");
      out.write("                    if (key == value) {\n");
      out.write("                        continue;\n");
      out.write("                    }\n");
      out.write("                    ar = mapToArray[key];\n");
      out.write("                    for (var j = 0; j < ar.length; j++) {\n");
      out.write("                        if (ar[j] == data[i]) {\n");
      out.write("                            isFound = true;\n");
      out.write("                            break;\n");
      out.write("                        }\n");
      out.write("                    }\n");
      out.write("                    if (isFound == true) {\n");
      out.write("                        break;\n");
      out.write("\n");
      out.write("                    }\n");
      out.write("\n");
      out.write("                }\n");
      out.write("                if (isFound == false) {\n");
      out.write("                    index = array.indexOf(data[i]);\n");
      out.write("                    if (index > -1) {\n");
      out.write("                        array.splice(index, 1);\n");
      out.write("                    }\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        $(\"#p-allLabTest\").select2('val', array);\n");
      out.write("\n");
      out.write("    });\n");
      out.write("});\n");
      out.write("\n");
      out.write("function callBack_after_full_date_labTestOrders_customized(){\n");
      out.write("    var i = 0, size = labTestList.length;\n");
      out.write("    for (i; i < size; i++) {\n");
      out.write("        $(\"#labTestOrders_customized\").multiselect(\"widget\").find(\":checkbox[value='\" + labTestList[i] + \"']\").attr(\"checked\", \"checked\");\n");
      out.write("        $(\"#labTestOrders_customized option[value='\" + labTestList[i] + \"']\").attr(\"selected\", 1);\n");
      out.write("    }\n");
      out.write("    $(\"#labTestOrders_customized\").multiselect(\"refresh\");\n");
      out.write("}\n");
      out.write("////////////////////////////////////\n");
      out.write("$(document).ready(function(){\n");
      out.write("\tvar noneSelectedTextJs=\"select customized LabTest\";\n");
      out.write("\tvar width = 70;\n");
      out.write("\t$(\"#labTestOrders_customized\").multiselect({\n");
      out.write("\t\t  selectedList: 60,\n");
      out.write("\t\t  hide: [\"slide\", 500],\n");
      out.write("\t  noneSelectedText:noneSelectedTextJs,\n");
      out.write("\t  checkAll: function(event, ui){\n");
      out.write("\t      var checkAllEventMethodName='checkAllCustomizeLabTestEvent';\n");
      out.write("\t      if(checkAllEventMethodName!=null || checkAllEventMethodName!='null'){\n");
      out.write("\t          if(typeof(window[checkAllEventMethodName])==\"function\"){\n");
      out.write("\t              window[checkAllEventMethodName](event, ui);\n");
      out.write("\t          }\n");
      out.write("\t      }\n");
      out.write("\t  },\n");
      out.write("\t  click:function(event,ui){\n");
      out.write("\t      var clickEventMethodName='clickCustomizeLabTestEvent';\n");
      out.write("\t      if(clickEventMethodName!=null || clickEventMethodName!='null'){\n");
      out.write("\t          if(typeof(window[clickEventMethodName])==\"function\"){\n");
      out.write("\t              window[clickEventMethodName](event, ui);\n");
      out.write("\t          }\n");
      out.write("\t      }\n");
      out.write("\t\n");
      out.write("\t  },\n");
      out.write("\t  optgrouptoggle:function(event,ui){\n");
      out.write("\t      var optgrouptoggleEventMethodName='optgrouptoggleCustomizeLabTestEvent';\n");
      out.write("\t      if(optgrouptoggleEventMethodName!=null || optgrouptoggleEventMethodName!='null'){\n");
      out.write("\t          if(typeof(window[optgrouptoggleEventMethodName])==\"function\"){\n");
      out.write("\t              window[optgrouptoggleEventMethodName](event, ui);\n");
      out.write("\t          }\n");
      out.write("\t      }\n");
      out.write("\t\n");
      out.write("\t  },\n");
      out.write("\t  uncheckAll:function(event,ui){\n");
      out.write("\t      var uncheckAllEventMethodName='unCheckAllCustomizeLabTestEvent';\n");
      out.write("\t      if(uncheckAllEventMethodName!=null || uncheckAllEventMethodName!='null'){\n");
      out.write("\t          if(typeof(window[uncheckAllEventMethodName])==\"function\"){\n");
      out.write("\t              window[uncheckAllEventMethodName](event, ui);\n");
      out.write("\t          }\n");
      out.write("\t      }\n");
      out.write("\t\n");
      out.write("\t  }\n");
      out.write("\t\n");
      out.write("\t}).multiselectfilter();\n");
      out.write("\t\n");
      out.write("\t$.getJSON(\"");
      if (_jspx_meth_c_005furl_005f2(_jspx_page_context))
        return;
      out.write("\" + \"clinic/customize/userLabTest/combo/loadSelectedLabTestGet\" , function(data) {\n");
      out.write("\t\t\t$(\"#labTestOrders_customized\").append(data.data);\n");
      out.write("\t\t\t$(\"#labTestOrders_customized\").multiselect(\"refresh\");\n");
      out.write("\t    var size=$(\".ui-multiselect\").size();\n");
      out.write("\t    for(var i=0;i<size;i++){\n");
      out.write("\t        $(\".ui-multiselect\")[i].style.width=\"100%\";\n");
      out.write("\t    }\n");
      out.write("\t        $(\".ui-multiselect-menu\").css(\"width\",'70%');\n");
      out.write("\t    if(typeof(window[\"callBack_after_full_date_\"+\"labTestOrders_customized\"])==\"function\"){\n");
      out.write("\t        window[\"callBack_after_full_date_\"+\"labTestOrders_customized\"]();\n");
      out.write("\t    }\n");
      out.write("\t});\n");
      out.write("});\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("    .ui-multiselect-menu {direction: ltr}\n");
      out.write("</style>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/pages/clinic/patient/VisitMobileBase/fileBaseItems/LabTestOrder.jsp(253,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f0.setValue("/");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/pages/clinic/patient/VisitMobileBase/fileBaseItems/LabTestOrder.jsp(517,15) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f1.setValue("/");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f2 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f2.setParent(null);
    // /WEB-INF/pages/clinic/patient/VisitMobileBase/fileBaseItems/LabTestOrder.jsp(649,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005furl_005f2.setValue("/");
    int _jspx_eval_c_005furl_005f2 = _jspx_th_c_005furl_005f2.doStartTag();
    if (_jspx_th_c_005furl_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f2);
    return false;
  }
}
