/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.28
 * Generated at: 2019-02-02 15:17:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages.clinic.basicInfo.Proficiency;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ResourceBundle;
import org.springframework.web.util.UrlPathHelper;

public final class ProficiencyView_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(10);
    _jspx_dependants.put("/WEB-INF/tags/footer.tag", Long.valueOf(1510663932000L));
    _jspx_dependants.put("/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar", Long.valueOf(1513760541684L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/matab/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/c.tld", Long.valueOf(1323245778000L));
    _jspx_dependants.put("/WEB-INF/tags/buttonPermission.tag", Long.valueOf(1510663931000L));
    _jspx_dependants.put("/WEB-INF/kendo-taglibs.tld", Long.valueOf(1510663914000L));
    _jspx_dependants.put("/WEB-INF/tags/message.tag", Long.valueOf(1510664025000L));
    _jspx_dependants.put("jar:file:/C:/Program%20Files/Apache%20Software%20Foundation/Tomcat%208.0/webapps/matab/WEB-INF/lib/javax.servlet.jsp.jstl-1.2.1.jar!/META-INF/fn.tld", Long.valueOf(1323245778000L));
    _jspx_dependants.put("/WEB-INF/tags/my-grid.tag", Long.valueOf(1510663933000L));
    _jspx_dependants.put("/WEB-INF/tags/exportToExcel.tag", Long.valueOf(1510664019000L));
    _jspx_dependants.put("/WEB-INF/tags/my-grid-column.tag", Long.valueOf(1510663925000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.ResourceBundle");
    _jspx_imports_classes.add("org.springframework.web.util.UrlPathHelper");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

	ResourceBundle resource = ResourceBundle.getBundle("application_fa");
	String basePath = new UrlPathHelper().getOriginatingRequestUri(request);
	request.setAttribute("basePath", basePath);
	String createUrl = basePath + "create";
	String menuSysCode = String.valueOf(request.getAttribute("menuSystemCode"));

      out.write("\n");
      out.write("\n");
      out.write("<div class=\"body-header\">\n");
      out.write("\t<ul class=\"uk-breadcrumb uk-h3\" id=\"breadcrumb\">\n");
      out.write("\t\t<li id=\"breadcrumb-main-section\"><span>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageTitle}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</span>\n");
      out.write("\t\t</li>\n");
      out.write("\t</ul>\n");
      out.write("\t<div id=\"header-toolbar\">\n");
      out.write("\t\t");
      if (_jspx_meth_base_005fbuttonPermission_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      out.write('	');
      if (_jspx_meth_base_005fbuttonPermission_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      if (_jspx_meth_base_005fmy_002dgrid_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_base_005ffooter_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    function updateProficiencyView(){\n");
      out.write("        var requestUrl = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" + \"/clinic/basicInfo/proficiency/updateProficiencyView\";\n");
      out.write("        $.getJSON(requestUrl, function (result) {\n");
      out.write("            if (result.state == \"success\") {\n");
      out.write("                alertify.success(result.message);\n");
      out.write("                //\n");
      out.write("                $(\"#grid\").data(\"kendoGrid\").dataSource.read();\n");
      out.write("            } else if (result.errorMsg == \"error\") {\n");
      out.write("                alertify.error(result.errorMsg);\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\t}\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_base_005fbuttonPermission_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:buttonPermission
    org.apache.jsp.tag.web.buttonPermission_tag _jspx_th_base_005fbuttonPermission_005f0 = (new org.apache.jsp.tag.web.buttonPermission_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fbuttonPermission_005f0);
    _jspx_th_base_005fbuttonPermission_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(22,2) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f0.setKey("global.crud.new");
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(22,2) name = classNames type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f0.setClassNames("uk-button uk-button-success");
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(22,2) name = id type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f0.setId("body-heade-create");
    _jspx_th_base_005fbuttonPermission_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fbuttonPermission_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005fbuttonPermission_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:buttonPermission
    org.apache.jsp.tag.web.buttonPermission_tag _jspx_th_base_005fbuttonPermission_005f1 = (new org.apache.jsp.tag.web.buttonPermission_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fbuttonPermission_005f1);
    _jspx_th_base_005fbuttonPermission_005f1.setJspContext(_jspx_page_context);
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(23,2) name = key type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f1.setKey("com.artonis.clinic.basicInfo.proficiency.btn.update");
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(23,2) name = classNames type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f1.setClassNames("uk-button uk-button-success");
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(23,2) name = id type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f1.setId("body-header-btn-update");
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(23,2) name = onClick type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fbuttonPermission_005f1.setOnClick("updateProficiencyView()");
    _jspx_th_base_005fbuttonPermission_005f1.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fbuttonPermission_005f1);
    return false;
  }

  private boolean _jspx_meth_base_005fmy_002dgrid_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:my-grid
    org.apache.jsp.tag.web.my_002dgrid_tag _jspx_th_base_005fmy_002dgrid_005f0 = (new org.apache.jsp.tag.web.my_002dgrid_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmy_002dgrid_005f0);
    _jspx_th_base_005fmy_002dgrid_005f0.setJspContext(_jspx_page_context);
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(27,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_005f0.setName("grid");
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(27,0) name = transportReadUrl type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_005f0.setTransportReadUrl((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${basePath}/grid-read", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(27,0) name = selectable type = java.lang.String reqTime = true required = false fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_005f0.setSelectable("single");
    _jspx_th_base_005fmy_002dgrid_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_base_005fmy_002dgrid_005f0, null));
    _jspx_th_base_005fmy_002dgrid_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmy_002dgrid_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005fmy_002dgrid_002dcolumn_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:my-grid-column
    org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0 = (new org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f0);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0.setParent(_jspx_parent);
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(28,1) name = title type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0.setTitle("com.artonis.clinic.basicInfo.proficiency.name");
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(28,1) name = field type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0.setField("name");
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(28,1) name = width type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0.setWidth("50px");
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f0);
    return false;
  }

  private boolean _jspx_meth_base_005fmy_002dgrid_002dcolumn_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:my-grid-column
    org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1 = (new org.apache.jsp.tag.web.my_002dgrid_002dcolumn_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f1);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1.setJspContext(_jspx_page_context);
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1.setParent(_jspx_parent);
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(29,1) name = title type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1.setTitle("com.artonis.clinic.basicInfo.proficiency.code");
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(29,1) name = field type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1.setField("code");
    // /WEB-INF/pages/clinic/basicInfo/Proficiency/ProficiencyView.jsp(29,1) name = width type = java.lang.String reqTime = true required = true fragment = false deferredValue = false expectedTypeName = java.lang.String deferredMethod = false methodSignature = null
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1.setWidth("50px");
    _jspx_th_base_005fmy_002dgrid_002dcolumn_005f1.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005fmy_002dgrid_002dcolumn_005f1);
    return false;
  }

  private boolean _jspx_meth_base_005ffooter_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  base:footer
    org.apache.jsp.tag.web.footer_tag _jspx_th_base_005ffooter_005f0 = (new org.apache.jsp.tag.web.footer_tag());
    _jsp_getInstanceManager().newInstance(_jspx_th_base_005ffooter_005f0);
    _jspx_th_base_005ffooter_005f0.setJspContext(_jspx_page_context);
    _jspx_th_base_005ffooter_005f0.doTag();
    _jsp_getInstanceManager().destroyInstance(_jspx_th_base_005ffooter_005f0);
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write('\n');
      out.write('	');
      if (_jspx_meth_base_005fmy_002dgrid_002dcolumn_005f0(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_base_005fmy_002dgrid_002dcolumn_005f1(_jspx_parent, _jspx_page_context))
        return true;
      out.write('\n');
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
